// angular/active-list/src/app/examples/timeline/timeline.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { ActiveList } from '@uiloos/core';
import { TimelineItem } from './types';

@Component({
  selector: 'timeline',
  templateUrl: './timeline.component.html',
  styleUrls: ['./timeline.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class TimelineComponent implements OnInit {
  @Input() items!: TimelineItem[];

  public timeline!: ActiveList<TimelineItem>;

  ngOnInit() {
    this.timeline = new ActiveList({
      contents: this.items,
      activeIndexes: [0],
    });
  }
}

<div class="timeline">
  <ol class="timeline-list">
    <li
      *ngFor="let content of timeline.contents"
      class="timeline-item"
      [ngClass]="{
        'seen': content.hasBeenActiveBefore,
        'current': content.isActive,
        'previous': content.isPrevious,
        'next': content.isNext
      }"
      (click)="content.activate()"
    >
      <span class="timeline-item-label">{{content.value.name}}</span>
      <span class="timeline-item-time">{{content.value.released}}</span>
    </li>
  </ol>

  <div class="timeline-content">
    <div class="timeline-content-controls">
      <button (click)="timeline.activatePrevious()" type="button">
        ‹
      </button>

      <h1>{{timeline.lastActivated?.name}}</h1>

      <button (click)="timeline.activateNext()" type="button">
        ›
      </button>
    </div>

    <p>
      {{timeline.lastActivated?.description}}
    </p>
  </div>
</div>

// react/active-list/src/examples/Timeline/Timeline.tsx
import { useActiveList } from "@uiloos/react";
import { TimelineItem } from "./types";
import "./Timeline.css";
import classNames from "classnames";

type Props = {
  items: TimelineItem[];
};

export function Timeline({ items }: Props) {
  const timeline = useActiveList({
    contents: items,
    active: items[0],
  });

  return (
    <div className="timeline">
      <ol className="timeline-list">
        {timeline.contents.map((content) => (
          <li
            key={content.value.id}
            className={classNames("timeline-item", {
              current: content.isActive,
              seen: content.hasBeenActiveBefore,
              next: content.isNext,
            })}
          >
            <button onClick={() => content.activate()}>
              <span className="timeline-item-label">{content.value.name}</span>
              <span className="timeline-item-time">
                {content.value.released}
              </span>
            </button>
          </li>
        ))}
      </ol>

      <div id="timeline-content-0" className="timeline-content">
        <div className="timeline-content-controls">
          <button
            className="timeline-previous"
            type="button"
            onClick={() => timeline.activatePrevious()}
          >
            ‹
          </button>

          <h1>{timeline.lastActivated?.name}</h1>

          <button
            className="timeline-next"
            type="button"
            onClick={() => timeline.activateNext()}
          >
            ›
          </button>
        </div>

        <p>{timeline.lastActivated?.description}</p>
      </div>
    </div>
  );
}
