// vue/view-channel/src/components/example-modals/PokemonModal.vue
<template>
  <p>{{ data.text }}</p>

  <ol>
    <li>
      <button @click="onPokemonClicked('bulbasaur')">Bulbasaur</button>
    </li>
    <li>
      <button @click="onPokemonClicked('squirtle')">Squirtle</button>
    </li>
    <li>
      <button @click="onPokemonClicked('charmander')">Charmander</button>
    </li>
  </ol>
</template>

<script lang="ts" setup>
import { ModalComponent } from "../modal/types";
import { ViewChannelView } from "@uiloos/core";
import { confirmDialog } from "../confirm-dialog/confirm-dialog-service";

export type PokemonModalResult = "bulbasaur" | "squirtle" | "charmander";

type PokemonModalComponentData = {
  text: string;
};

interface Props {
  view: ViewChannelView<any, PokemonModalResult>;
  data: PokemonModalComponentData;
}

const { view } = defineProps<Props>();

function onPokemonClicked(pokemon: PokemonModalResult) {
  view.dismiss(pokemon);
}
</script>

// angular/view-channel/src/app/examples/example-modals/pokemon-modal/pokemon-modal.component.ts
import { Component } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { ModalComponent, ModalData } from '../../modal/types';

export type PokemonModalResult = 'bulbasaur' | 'squirtle' | 'charmander';

export type PokemonModalComponentData = {
  text: string;
};

@Component({
  selector: 'pokemon-modal',
  templateUrl: './pokemon-modal.component.html',
  standalone: true
})
export class PokemonModalComponent
  implements ModalComponent<PokemonModalResult, PokemonModalComponentData> {
  public view!: ViewChannelView<
    ModalData<PokemonModalComponentData>,
    PokemonModalResult
  >;

  public data!: PokemonModalComponentData;

  onPokemonClicked(pokemon: PokemonModalResult) {
    this.view.dismiss(pokemon);
  }
}

<p>{{ data.text }}</p>

<ol>
  <li>
    <button (click)="onPokemonClicked('bulbasaur')">
      Bulbasaur
    </button>
  </li>
  <li>
    <button (click)="onPokemonClicked('squirtle')">Squirtle</button>
  </li>
  <li>
    <button (click)="onPokemonClicked('charmander')">
      Charmander
    </button>
  </li>
</ol>
