// angular/date-gallery/src/app/examples/calendar/week-calendar/components/week-event/week-event.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  TemplateRef,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import {
  DateGallery,
  DateGalleryEvent,
  createDateGallerySubscriber,
  UnsubscribeFunction,
} from '@uiloos/core';
import { EventData, ariaLabelForEvent } from '../../../events';
import { timeFormatter } from '../../../../formatters';
import { START_HOUR, HEIGHT } from '../../config';
import { emptyImage, yiq, getMinutesSinceStart } from '../../../utils';

@Component({
  selector: 'week-event',
  templateUrl: './week-event.component.html',
  styleUrl: './week-event.component.css',
  standalone: true,
  imports: [CommonModule],
})
export class WeekEventComponent implements OnInit, OnDestroy, AfterViewInit {
  /* 
    Needed to project the <li> directly into the <ul> so the CSS
    grid works. Angular by default adds an element to the DOM
    to track changes, which breaks the CSS grid.
    
    In the future you might use:

    :host {
     display: contents;
    }

    What `display: contents` does is treat the first child of a
    element as the element itself. This would be an ideal solution
    for this problem, but it is not fully supported yet without 
    accessibility bugs see: https://caniuse.com/css-display-contents.
  */
  @ViewChild('template', { static: true }) template!: TemplateRef<HTMLElement>;

  @Input() date!: Date;
  @Input() dateGallery!: DateGallery<EventData>;
  @Input() event!: DateGalleryEvent<EventData>;
  @Input() gridColumn!: string;

  @Output() click = new EventEmitter<void>();

  public yiq: typeof yiq;
  public ariaLabelForEvent: typeof ariaLabelForEvent;

  public title = '';
  public time = '';
  public gridRow = '';
  public showStartTime = false;
  public showEndTime = false;

  public timeFormatter: Intl.DateTimeFormat;

  constructor(private viewContainerRef: ViewContainerRef) {
    this.yiq = yiq;
    this.ariaLabelForEvent = ariaLabelForEvent;
    this.timeFormatter = timeFormatter;
  }

  private unsubscribe: UnsubscribeFunction | null = null;

  ngOnInit(): void {
    this.viewContainerRef.createEmbeddedView(this.template);

    this.sync();

    const self = this;
    this.unsubscribe = this.dateGallery.subscribe(
      createDateGallerySubscriber({
        onEventDataChanged(e) {
          if (e.data.id === self.event.data.id) {
            self.sync();
          }
        },
        onEventMoved(e) {
          if (e.event.data.id === self.event.data.id) {
            self.sync();
          }
        },
      }),
    );
  }

  ngAfterViewInit(): void {
    /*
      Warning dirty hack: 

      In the `WeekCalendar` we render a `DayGrid` which contains the `WeekEvent`
      components, whenever a `WeekEvent` component is dragged over a `DayGrid`
      it is moved to that day, the code to actually move is here in 
      `WeekEvent`'s `onDrag` in the `hoveredDayEl` logic.

      This causes Angular to re-render and since the `WeekEvent` is no longer 
      the child of his old `DayGrid` it is removed from the DOM and re-created.

      But this causes a problem for us: if we used Angular `on:drag`, the 
      dragging stops. When an element is removed Angular no longer sends 
      dragging events. This makes sense since the element from Angular 
      point of view does not exist any longer. This is not what we want, 
      we want to keep dragging the element!

      Luckily for us the `ondrag` from JS does not care if an element is 
      no longer in the DOM.
      
      So we manually keep it in memory by setting an `ondrag` on the element 
      behind Angular's back, and cleaning it up manually. This way the 
      element will stay in memory, due to us keeping a reference to it.
    */
    this.eventRef.nativeElement.ondrag = (e) => {
      this.onDrag(e);
    };

    this.eventRef.nativeElement.ondragend = (e) => {
      if (this.eventRef.nativeElement) {
        this.eventRef.nativeElement.ondrag = null;
        this.eventRef.nativeElement.ondragend = null;
      }
    };
  }

  ngOnDestroy(): void {
    if (this.unsubscribe) {
      this.unsubscribe();
    }
  }

  @ViewChild('eventRef') eventRef!: ElementRef<HTMLLinkElement>;
  @ViewChild('startDragRef') startDragRef!: ElementRef<HTMLSpanElement>;
  @ViewChild('endDragRef') endDragRef!: ElementRef<HTMLSpanElement>;

  public startDraggable = true;
  public endDraggable = true;

  public dragData = {
    yAtDragStart: 0,
    dragStartTime: 0,
    dragEndTime: 0,
    mode: '',
    draggedEvent: this.event,
  };

  // When the drag starts store information about which event is dragged
  onDragStart(e: DragEvent) {
    e.stopPropagation();

    // Store what the mouse position was at the start of the drag.
    // Used to calulate how many minutes the user wants the event
    // to move.
    this.dragData.yAtDragStart = e.clientY;

    // Set store the original start and end time for when
    // the dragging began. This way we always know the
    // original times even after we "move" the event.
    this.dragData.dragStartTime = new Date(this.event.startDate).getTime();
    this.dragData.dragEndTime = new Date(this.event.endDate).getTime();

    if (e.target === this.eventRef.nativeElement) {
      this.dragData.mode = 'event';
    } else if (e.target === this.startDragRef.nativeElement) {
      this.dragData.mode = 'start';
    } else {
      this.dragData.mode = 'end';
    }

    this.dragData.draggedEvent = this.event;

    if (e.dataTransfer) {
      // Set the drag image to an empty image. Because we are
      // going to continuously "move" the event we do not need
      // a "ghost".
      e.dataTransfer.setDragImage(emptyImage, 0, 0);
    }
  }

  // When the the event is dragged alter the time period of the vent.
  onDrag(e: DragEvent) {
    e.stopPropagation();

    // Only do something on drag if we are the event that is
    // being dragged
    if (this.dragData.draggedEvent !== this.event) {
      return;
    }

    // Sometimes the clientX is suddenly zero on drag end,
    // do nothing if this is the case. Otherwise the event
    // will suddenly jump to the previous day
    if (e.clientX === 0) {
      return;
    }

    // The number of minutes moved is the amount of pixels away
    // the cursor (clientY) is from the clientY at the start of
    // the drag start.
    const minutesMoved = e.clientY - this.dragData.yAtDragStart;

    // Find the dayEl element the cursor is currently hovering
    // over, if it has found one the date of the event must
    // be changed.
    const hoveredDayEl = document
      .elementsFromPoint(e.clientX, e.clientY)
      .find((element) => {
        return element.classList.contains('calendar-week-day-grid');
      });

    // The user might mouse out of the calendar, in that case default
    // to the current startDate
    let movedToDate = this.event.startDate;
    if (hoveredDayEl && hoveredDayEl instanceof HTMLElement) {
      const date = hoveredDayEl.dataset['date'] ?? '0';

      movedToDate = new Date(parseInt(date, 10));
    }

    // Move by an increment of 5 minutes, to create a snap effect
    if (
      minutesMoved % 5 === 0 ||
      !this.dateGallery.isSameDay(movedToDate, this.event.startDate)
    ) {
      // Date constructor wants milliseconds since 1970
      const msMoved = minutesMoved * 60 * 1000;

      // Note: moving the event will cause the entire DOM to be ripped
      // to shreds and be rebuilt. So the 5 minute snap effect is
      // also a performance boost.

      if (this.dragData.mode === 'event') {
        const duration =
          this.dragData.dragEndTime - this.dragData.dragStartTime;

        // First update to the new start time
        const startDate = new Date(this.dragData.dragStartTime + msMoved);

        /* 
          Second update the start date.
          
          We do this via a call to `setFullYear` with all date parts. 
          Setting them in separate calls like this:
          
          startDate.setFullYear(movedToDate.getFullYear());
          startDate.setMonth(movedToDate.getMonth());
          startDate.setDate(movedToDate.getDate());

          Could cause a very nasty bug were it could set the date to a non 
          existing date. But only for very few dates were the size of the 
          month differs from the month the date is moved into.
          
          The bug can be triggered like so:

          const d = new Date(2024, 30, 1); // 1/30/2024 - Feb 30th 2024
          d.setFullYear(2025) // Date is now 1/30/2025
          d.setMonth(2); // Date tries to be 2/30/2025, which doesn't exist, and rolls over to 3/1/2025
          d.setDate(15); // Date is now 3/15/2025 instead of 2/15/2025 as expected

          The above I credit to Marc Hughes see: https://github.com/Simon-Initiative/oli-torus/pull/4614
        */
        startDate.setFullYear(
          movedToDate.getFullYear(),
          movedToDate.getMonth(),
          movedToDate.getDate(),
        );

        // Move both start and end times with the same values
        // so the duration of the event stays the same.
        this.event.move({
          startDate: startDate,
          endDate: new Date(startDate.getTime() + duration),
        });
      } else if (this.dragData.mode === 'start') {
        // Move only the start time
        this.event.move({
          startDate: new Date(this.dragData.dragStartTime + msMoved),
          endDate: this.event.endDate,
        });
      } else {
        // Move only the end time
        this.event.move({
          startDate: this.event.startDate,
          endDate: new Date(this.dragData.dragEndTime + msMoved),
        });
      }
    }
  }

  sync() {
    /*
    An event that spans multiple days is rendered once in each
    day the event occurs.

    On dates that match the startDate and endDate we make draggable.
  */
    if (this.event.spansMultipleDays) {
      if (this.dateGallery.isSameDay(this.event.startDate, this.date)) {
        // When the event starts on this day, make it span the
        // entire day, as we know it does not end on this day.
        const start = getMinutesSinceStart(this.event.startDate, START_HOUR);
        this.gridRow = `${start + 1} / ${HEIGHT}`;

        // No end time indicator as it is on another day
        this.endDraggable = false;

        // Show start time only on first day
        this.showStartTime = true;
      } else if (this.dateGallery.isSameDay(this.event.endDate, this.date)) {
        // When the event ends on this day start it at midnight, since
        // we know it started on a previous day.
        const end = getMinutesSinceStart(this.event.endDate, START_HOUR);

        this.gridRow = `1 / ${end + 2}`;

        // No start time drag indicator as it is on another day
        this.startDraggable = false;

        // Show end time only on last day
        this.showEndTime = true;
      } else {
        // When the event is during this whole day take up all space
        this.gridRow = `1 / ${HEIGHT}`;

        // No start / end drag indicator as it is on another day
        this.startDraggable = false;
        this.endDraggable = false;
      }
    } else {
      // The event is contained within this day.

      const start = getMinutesSinceStart(this.event.startDate, START_HOUR);
      const end = getMinutesSinceStart(this.event.endDate, START_HOUR);

      this.gridRow = `${start + 1} / ${end + 1}`;

      // When fully in this day show both times
      this.showStartTime = true;
      this.showEndTime = true;
    }
  }

  onClick(e: Event) {
    e.stopPropagation();
    this.click.emit();
  }
}

<ng-template #template>
  <li
    #eventRef
    class="calendar-week-event"
    [ngStyle]="{
      'background-color': event.data.color,
      'gridColumn': gridColumn,
      'gridRow': gridRow,
    }"
    (click)="onClick($event)"
    [draggable]="event.spansMultipleDays === false"
    (dragstart)="onDragStart($event)"
  >
    <button
      [ngStyle]="{
        'background-color': event.data.color,
        color: yiq(event.data.color),
      }"
      attr.aria-label="{{ ariaLabelForEvent(event) }}"
    >
      <span
        #startDragRef
        class="drag-indicator"
        [draggable]="startDraggable"
        (dragstart)="onDragStart($event)"
        (drag)="onDrag($event)"
      ></span>

      <span class="text-container">
        <span class="inner-text-container">
          <b *ngIf="showStartTime">{{
            timeFormatter.format(event.startDate)
          }}</b>
          <i [title]="event.data.title">{{ event.data.title }}</i>
          <span>{{ event.data.description }}</span>
        </span>

        <b *ngIf="showEndTime" class="end-time">{{
          timeFormatter.format(event.endDate)
        }}</b>
      </span>

      <span
        #endDragRef
        class="drag-indicator"
        [draggable]="endDraggable"
        (dragstart)="onDragStart($event)"
        (drag)="onDrag($event)"
      ></span>
    </button>
  </li>
</ng-template>

// react/date-gallery/src/examples/Calendar/WeekCalendar/components/WeekEvent.tsx
import React, { useRef, DragEvent, useEffect } from "react";
import { DateGallery, DateGalleryEvent } from "@uiloos/core";
import { ariaLabelForEvent, EventData } from "../../events";
import { yiq, getMinutesSinceStart, emptyImage } from "../../utils";
import { timeFormatter } from "../../../formatters";
import { HEIGHT, START_HOUR } from "../config";

type Props = {
  date: Date;
  dateGallery: DateGallery<EventData>;
  event: DateGalleryEvent<EventData>;
  gridColumn: string;
  onClick(): void;
};

export function WeekEvent({
  event,
  gridColumn,
  dateGallery,
  date,
  onClick,
}: Props) {
  const eventRef = useRef<HTMLLIElement | null>(null);
  const startDragRef = useRef<HTMLSpanElement | null>(null);
  const endDragRef = useRef<HTMLSpanElement | null>(null);

  let startDraggable = true;
  let endDraggable = true;

  let dragData = useRef({
    yAtDragStart: 0,
    dragStartTime: 0,
    dragEndTime: 0,
    mode: "",
  });

  /*
    Warning dirty hack: 

    In the `WeekCalendar` we render a `DayGrid` which contains the `WeekEvent`
    components, whenever a `WeekEvent` component is dragged over a `DayGrid`
    it is moved to that day, the code to actually move is here in 
    `WeekEvent`'s `onDrag` in the `hoveredDayEl` logic.

    This causes React to re-render and since the `WeekEvent` is no longer 
    the child of his old `DayGrid` it is removed from the DOM and re-created.

    But this causes a problem for us: if we used Reacts `onDrag`, the 
    dragging stops. When an element is removed React no longer sends 
    dragging events. This makes sense since the element from Reacts 
    point of view does not exist any longer. This is not what we want, 
    we want to keep dragging the element!

    Luckily for us the `ondrag` from JS does not care if an element is 
    no longer in the DOM.
    
    So we manually keep it in memory by setting an `ondrag` on the element 
    behind React's back, and cleaning it up manually. This way the 
    element will stay in memory, due to us keeping a reference to it.
  */
  useEffect(() => {
    if (eventRef.current) {
      eventRef.current.ondrag = (e) => {
        // @ts-expect-error allow me to pass in a native drag
        onDrag(e);
      };

      return () => {
        if (eventRef.current) {
          eventRef.current.ondrag = null;
        }
      };
    }
  }, []);

  // When the drag starts store information about which event is dragged
  function onDragStart(e: DragEvent<HTMLElement>) {
    e.stopPropagation();

    // Store what the mouse position was at the start of the drag.
    // Used to calulate how many minutes the user wants the event
    // to move.
    dragData.current.yAtDragStart = e.clientY;

    // Set store the original start and end time for when
    // the dragging began. This way we always know the
    // original times even after we "move" the event.
    dragData.current.dragStartTime = new Date(event.startDate).getTime();
    dragData.current.dragEndTime = new Date(event.endDate).getTime();

    if (e.target === eventRef.current) {
      dragData.current.mode = "event";
    } else if (e.target === startDragRef.current) {
      dragData.current.mode = "start";
    } else {
      dragData.current.mode = "end";
    }

    // Set the drag image to an empty image. Because we are
    // going to continuously "move" the event we do not need
    // a "ghost".
    e.dataTransfer.setDragImage(emptyImage, 0, 0);
  }

  // When the the event is dragged alter the time period of the vent.
  function onDrag(e: DragEvent<HTMLElement>) {
    e.stopPropagation();

    // Sometimes the clientX is suddenly zero on drag end,
    // do nothing if this is the case. Otherwise the event
    // will suddenly jump to the previous day
    if (e.clientX === 0) {
      return;
    }

    // The number of minutes moved is the amount of pixels away
    // the cursor (clientY) is from the clientY at the start of
    // the drag start.
    const minutesMoved = e.clientY - dragData.current.yAtDragStart;

    // Find the dayEl element the cursor is currently hovering
    // over, if it has found one the date of the event must
    // be changed.
    const hoveredDayEl = document
      .elementsFromPoint(e.clientX, e.clientY)
      .find((element) => {
        return element.classList.contains("calendar-week-day-grid");
      });

    // The user might mouse out of the calendar, in that case default
    // to the current startDate
    let movedToDate = event.startDate;
    if (hoveredDayEl && hoveredDayEl instanceof HTMLElement) {
      const date = hoveredDayEl.dataset.date ?? "0";

      movedToDate = new Date(parseInt(date, 10));
    }

    // Move by an increment of 5 minutes, to create a snap effect
    if (
      minutesMoved % 5 === 0 ||
      !dateGallery.isSameDay(movedToDate, event.startDate)
    ) {
      // Date constructor wants milliseconds since 1970
      const msMoved = minutesMoved * 60 * 1000;

      // Note: moving the event will cause the entire DOM to be ripped
      // to shreds and be rebuilt. So the 5 minute snap effect is
      // also a performance boost.

      if (dragData.current.mode === "event") {
        const duration =
          dragData.current.dragEndTime - dragData.current.dragStartTime;

        // First update to the new start time
        const startDate = new Date(dragData.current.dragStartTime + msMoved);

        /* 
          Second update the start date.
          
          We do this via a call to `setFullYear` with all date parts. 
          Setting them in separate calls like this:
          
          startDate.setFullYear(movedToDate.getFullYear());
          startDate.setMonth(movedToDate.getMonth());
          startDate.setDate(movedToDate.getDate());

          Could cause a very nasty bug were it could set the date to a non 
          existing date. But only for very few dates were the size of the 
          month differs from the month the date is moved into.
          
          The bug can be triggered like so:

          const d = new Date(2024, 30, 1); // 1/30/2024 - Feb 30th 2024
          d.setFullYear(2025) // Date is now 1/30/2025
          d.setMonth(2); // Date tries to be 2/30/2025, which doesn't exist, and rolls over to 3/1/2025
          d.setDate(15); // Date is now 3/15/2025 instead of 2/15/2025 as expected

          The above I credit to Marc Hughes see: https://github.com/Simon-Initiative/oli-torus/pull/4614
        */
        startDate.setFullYear(
          movedToDate.getFullYear(),
          movedToDate.getMonth(),
          movedToDate.getDate(),
        );

        // Move both start and end times with the same values
        // so the duration of the event stays the same.
        event.move({
          startDate: startDate,
          endDate: new Date(startDate.getTime() + duration),
        });
      } else if (dragData.current.mode === "start") {
        // Move only the start time
        event.move({
          startDate: new Date(dragData.current.dragStartTime + msMoved),
          endDate: event.endDate,
        });
      } else {
        // Move only the end time
        event.move({
          startDate: event.startDate,
          endDate: new Date(dragData.current.dragEndTime + msMoved),
        });
      }
    }
  }

  let gridRow = "";
  let showStartTime = false;
  let showEndTime = false;

  /*
    An event that spans multiple days is rendered once in each 
    day the event occurs. 
    
    On dates that match the startDate and endDate we make draggable.
  */
  if (event.spansMultipleDays) {
    if (dateGallery.isSameDay(event.startDate, date)) {
      // When the event starts on this day, make it span the
      // entire day, as we know it does not end on this day.
      const start = getMinutesSinceStart(event.startDate, START_HOUR);
      gridRow = `${start + 1} / ${HEIGHT}`;

      // No end time indicator as it is on another day
      endDraggable = false;

      // Show start time only on first day
      showStartTime = true;
    } else if (dateGallery.isSameDay(event.endDate, date)) {
      // When the event ends on this day start it at midnight, since
      // we know it started on a previous day.
      const end = getMinutesSinceStart(event.endDate, START_HOUR);

      gridRow = `1 / ${end + 2}`;

      // No start time drag indicator as it is on another day
      startDraggable = false;

      // Show end time only on last day
      showEndTime = true;
    } else {
      // When the event is during this whole day take up all space
      gridRow = `1 / ${HEIGHT}`;

      // No start / end drag indicator as it is on another day
      startDraggable = false;
      endDraggable = false;
    }
  } else {
    // The event is contained within this day.

    const start = getMinutesSinceStart(event.startDate, START_HOUR);
    const end = getMinutesSinceStart(event.endDate, START_HOUR);

    gridRow = `${start + 1} / ${end + 1}`;

    // When fully in this day show both times
    showStartTime = true;
    showEndTime = true;
  }

  return (
    <li
      ref={eventRef}
      className="calendar-week-event"
      style={{ backgroundColor: event.data.color, gridColumn, gridRow }}
      onClick={(e) => {
        e.stopPropagation();
        onClick();
      }}
      draggable={event.spansMultipleDays === false}
      onDragStart={onDragStart}
    >
      <button
        style={{
          backgroundColor: event.data.color,
          color: yiq(event.data.color),
        }}
        aria-label={ariaLabelForEvent(event)}
      >
        <span
          ref={startDragRef}
          className="drag-indicator"
          draggable={startDraggable}
          onDragStart={onDragStart}
          onDrag={onDrag}
        ></span>
        <span className="text-container">
          <span className="inner-text-container">
            {showStartTime ? (
              <b>{timeFormatter.format(event.startDate)}</b>
            ) : null}
            <i title={event.data.title}>{event.data.title}</i>
            <p>{event.data.description}</p>
          </span>
          {showEndTime ? (
            <b className="end-time">{timeFormatter.format(event.endDate)}</b>
          ) : null}
        </span>
        <span
          ref={endDragRef}
          className="drag-indicator"
          draggable={endDraggable}
          onDragStart={onDragStart}
          onDrag={onDrag}
        ></span>
      </button>
    </li>
  );
}
