// angular/typewriter/src/app/app.component.ts
import { Component } from "@angular/core";
import { InteractiveComponent } from "./examples/interactive/interactive.component";
import { KaraokeComponent } from "./examples/karaoke/karaoke.component";
import { LullabyComponent } from "./examples/lullaby/lullaby.component";
import { MovieComponent } from "./examples/movie/movie.component";
import { MulticursorComponent } from "./examples/multicursor/multicursor.component";
import { SentencesComponent } from "./examples/sentences/sentences.component";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  standalone: true,
  imports: [
    SentencesComponent,
    InteractiveComponent,
    KaraokeComponent,
    LullabyComponent,
    MovieComponent,
    MulticursorComponent
  ]
})
export class AppComponent {}

<div class="main">
  <sentences></sentences>
  <multicursor></multicursor>
  <movie></movie>
  <lullaby></lullaby>
  <karaoke></karaoke>
  <interactive></interactive>
</div>

// react/typewriter/src/App.tsx
import { Interactive } from "./Interactive/Interactive";
import { Karaoke } from "./Karaoke/Karaoke";
import { Lullaby } from "./Lullaby/Lullaby";
import { Movie } from "./Movie/Movie";
import { Multicursor } from "./Multicursor/Multicursor";
import { Sentences } from "./Sentences/Sentences";

export default function App() {
  return (
    <div className="App">
      <Sentences />
      <Multicursor />
      <Movie />
      <Lullaby />
      <Karaoke />
      <Interactive />
    </div>
  );
}
