// vue/active-list/src/examples/ClassicCarousel/ProgressButton.vue
<template>
  <button
    ref="buttonElement"
    class="progress-button"
    :class="{ active: isActive }"
    @click="$emit('click')"
  ></button>
</template>

<script setup lang="ts">
import { ref, watchEffect } from "vue";

interface Props {
  duration: number;
  isActive: boolean;
  isPlaying: boolean;
}

const props = defineProps<Props>();

let buttonElement = ref<HTMLButtonElement | null>(null);

watchEffect(() => {
  if (buttonElement.value) {
    if (props.isActive) {
      buttonElement.value.style.animation = `progress ${props.duration}ms linear`;
    } else {
      buttonElement.value.style.animation = "";
    }
  }
});

watchEffect(() => {
  if (buttonElement.value) {
    if (props.isPlaying) {
      buttonElement.value.style.animationPlayState = "running";
    } else {
      buttonElement.value.style.animationPlayState = "paused";
    }
  }
});
</script>

<style>
.progress-button {
  width: 30px;
  background-color: gray;
  height: 4px;
  border: none;
  cursor: pointer;
}

.progress-button.active {
  background: linear-gradient(
    to right,
    rgb(107 33 168) 50%,
    rgb(102, 102, 102) 50%
  );
  background-size: 200% 100%;
}

@keyframes -global-progress {
  from {
    background-position: right bottom;
  }
  to {
    background-position: left bottom;
  }
}
</style>

// svelte/active-list/src/examples/ClassicCarousel/ProgressButton.svelte
<script lang="ts">
  import { ActiveListContent } from '@uiloos/core';
  import type { Slide } from './types';

  export let content: ActiveListContent<Slide>;

  let buttonElement: HTMLButtonElement;

  $: onActiveChanged(
    content.isActive,
    content.activeList.autoPlay.duration,
    buttonElement
  );
  $: onPlayingChanged(content.activeList.autoPlay.isPlaying, buttonElement);

  function onActiveChanged(
    isActive: boolean,
    duration: number,
    buttonElement: HTMLButtonElement
  ) {
    if (buttonElement) {
      if (isActive) {
        buttonElement.style.animation = `progress ${duration}ms linear`;
      } else {
        buttonElement.style.animation = '';
      }
    }
  }

  function onPlayingChanged(
    isPlaying: boolean,
    buttonElement: HTMLButtonElement
  ) {
    if (buttonElement) {
      if (isPlaying) {
        buttonElement.style.animationPlayState = 'running';
      } else {
        buttonElement.style.animationPlayState = 'paused';
      }
    }
  }
</script>

<button
  bind:this={buttonElement}
  class="progress-button"
  class:active={content.isActive}
  on:click={() => content.activate()}
></button>

<style>
  .progress-button {
    width: 30px;
    background-color: gray;
    height: 4px;
    border: none;
    cursor: pointer;
  }

  .progress-button.active {
    background: linear-gradient(
      to right,
      rgb(107 33 168) 50%,
      rgb(102, 102, 102) 50%
    );
    background-size: 200% 100%;
  }

  @keyframes -global-progress {
    from {
      background-position: right bottom;
    }
    to {
      background-position: left bottom;
    }
  }
</style>
