// svelte/view-channel/src/routes/components/example-modals/PlanetModal.svelte
<small>{ data.plea }</small>

<ol>
  <li>
    <button on:click={() => destroy('earth')}>Earth</button>
  </li>
  <li>
    <button on:click={() => destroy('mars')}>Mars</button>
  </li>
  <li>
    <button on:click={() => destroy('venus')}>Venus</button>
  </li>
</ol>

<script lang="ts">
import type { ViewChannelView } from "@uiloos/core";
import { confirmDialog } from "../confirm-dialog/confirm-dialog-service";

type PlanetModalResult = "earth" | "mars" | "venus";

type PlanetModalComponentData = {
  plea: string;
};

export let view: ViewChannelView<unknown, PlanetModalResult>;
export let data: PlanetModalComponentData;

async function destroy(planet: PlanetModalResult) {
  const confirmation = await confirmDialog(
    `Are you sure you want to destroy ${planet}`
  );

  if (confirmation) {
    view.dismiss(planet);
  }
}
</script>

// angular/view-channel/src/app/examples/example-modals/planet-modal/planet-modal.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { ModalComponent, ModalData } from '../../modal/types';
import { ConfirmationDialogService } from '../../confirmation-dialog/confirmation-dialog.service';

type PlanetModalResult = 'earth' | 'mars' | 'venus';

type PlanetModalComponentData = {
  plea: string;
};

@Component({
  selector: 'planet-modal',
  templateUrl: './planet-modal.component.html',
  standalone: true
})
export class PlanetModalComponent
  implements ModalComponent<PlanetModalResult, PlanetModalComponentData> {
  @Input() view!: ViewChannelView<
    ModalData<PlanetModalComponentData>,
    PlanetModalResult
  >;

  @Input() data!: PlanetModalComponentData;

  private confirmationDialogService: ConfirmationDialogService;

  constructor(confirmationDialogService: ConfirmationDialogService) {
    this.confirmationDialogService = confirmationDialogService;
  }

  async destroy(planet: PlanetModalResult) {
    const confirmation = await this.confirmationDialogService.confirmDialog(
      `Are you sure you want to destroy ${planet}`
    );

    if (confirmation) {
      this.view.dismiss(planet);
    }
  }
}

<small>{{data.plea}}</small>

<ol>
  <li>
    <button (click)="destroy('earth')">Earth</button>
  </li>
  <li>
    <button (click)="destroy('mars')">Mars</button>
  </li>
  <li>
    <button (click)="destroy('venus')">Venus</button>
  </li>
</ol>
