// angular/active-list/src/app/examples/selector/condiment.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { ActiveListContent } from '@uiloos/core';
import { Condiment } from './types';

@Component({
  selector: 'condiment',
  templateUrl: './condiment.component.html',
  styleUrls: ['./condiment.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class CondimentComponent {
  @Input() content!: ActiveListContent<Condiment>;
}

 <button
    class="condiment"
    [ngClass]="{ selected: content.isActive }"
    (click)="content.toggle()"
  >
    <h4>{{ content.value.name }}</h4>
    <p>{{ content.value.description }}</p>
    <b>${{ content.value.price }}</b>
  </button>

// react/active-list/src/examples/Selector/Condiment.tsx
import classNames from "classnames";
import { ActiveListContent } from "@uiloos/core";
import { Condiment as CondimentType } from "./types";

type Props = {
  content: ActiveListContent<CondimentType>;
};

export function Condiment({ content }: Props) {
  const condiment = content.value;

  return (
    <button
      className={classNames("condiment", {
        selected: content.isActive,
      })}
      onClick={() => content.toggle()}
    >
      <h4>{condiment.name}</h4>
      <p>{condiment.description}</p>
      <b>${condiment.price}</b>
    </button>
  );
}
