// angular/view-channel/src/app/examples/modal/modal-wrapper/modal-wrapper.component.ts
import {
  Component,
  HostListener,
  Input,
  OnInit,
  ViewChild
} from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { modalCancelled } from '../modal.service';
import { ModalData } from '../types';
import { ModalLoaderDirective } from '../modal-loader.directive';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'modal-wrapper',
  templateUrl: './modal-wrapper.component.html',
  styleUrls: ['./modal-wrapper.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    ModalLoaderDirective
  ]
})
export class ModalWrapperComponent implements OnInit {
  @Input() view!: ViewChannelView<ModalData<any>, any>;

  @ViewChild(ModalLoaderDirective, { static: true })
  modalLoader!: ModalLoaderDirective;

  ngOnInit() {
    const Component = this.view.data.component;

    // Programmatically instantiate the given Component
    const component = this.modalLoader.viewContainerRef.createComponent(
      Component
    );

    // Now set the props so the modal works
    component.instance.view = this.view;
    component.instance.data = this.view.data.data;
  }

  @HostListener('document:keydown.escape')
  onCancelClicked() {
    this.view.dismiss(modalCancelled);
  }
}

<div class="modal-backdrop" (click)="onCancelClicked()"></div>

<div
  class="modal"
  [attr.aria-label]="view.data.info.title"
  aria-describedby="modal-description"
>
  <button
    class="modal-close"
    (click)="onCancelClicked()"
    aria-label="Close modal"
  >
    ✖
  </button>

  <h1>{{ view.data.info.title }}</h1>

  <p id="modal-description">{{ view.data.info.description }}</p>

  <ng-template modalLoader=""></ng-template>
</div>

// react/view-channel/src/Modal/ModalWrapper.tsx
import { ReactNode, useEffect } from 'react';
import { ViewChannelView } from '@uiloos/core';
import { modalCancelled } from './modal-service';
import { ModalData } from './types';

type Props = {
  children: ReactNode;
  view: ViewChannelView<ModalData<any, any>, any>;
};

/**
 * A component which contains the common things in every modal:
 * a backdrop and a close button.
 */
export function ModalWrapper({ view, children }: Props) {
  function onCancelClicked() {
    view.dismiss(modalCancelled);
  }

  useEffect(() => {
    function closeOnEscape(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        onCancelClicked();
      }
    }

    document.addEventListener('keydown', closeOnEscape);

    return () => {
      document.removeEventListener('keydown', closeOnEscape);
    };
  });

  return (
    <>
      <div className="modal-backdrop" onClick={onCancelClicked}></div>

      <div
        className="modal"
        role="dialog"
        aria-label={view.data.info.title}
        aria-describedby="modal-description"
      >
        <button
          className="modal-close"
          onClick={onCancelClicked}
          aria-label="Close modal"
        >
          ✖
        </button>

        <h1>{view.data.info.title}</h1>

        <p id="modal-description">{view.data.info.description}</p>

        {children}
      </div>
    </>
  );
}
