// svelte/view-channel/src/routes/components/notification/NotificationViewChannel.svelte

<div class="notifications">
  {#if $notifications.views.length}
    <div>
      <button on:click={dismissAll}>Clear all</button>
    </div>
  {:else}
    <p>No notifications yet</p>
  {/if}

  <div role="status" aria-live="polite">
    {#each $notifications.views as view}
      <Notification view={view} />
    {/each}
  </div>
</div>

<script lang="ts">
import Notification from "./Notification.svelte";
import { createViewChannelStore } from "@uiloos/svelte";
import { notificationChannel } from "./notification-service";

// Via createViewChannelStore we make sure this component re-renders
// whenever the ViewChannel changes.
const notifications = createViewChannelStore(notificationChannel);

function dismissAll() {
  $notifications.dismissAll(undefined);
}
</script>

<style>
.notifications {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 6px 0;
}
</style>

// vue/view-channel/src/components/notification/NotificationViewChannel.vue
<template>
  <div class="notifications">
    <div v-if="notifications.views.length">
      <button @click="dismissAll()">Clear all</button>
    </div>
    <p v-else>No notifications yet</p>

    <div role="status" aria-live="polite">
      <Notification
        v-for="view in notifications.views"
        :key="view.data.id"
        :view="view"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import Notification from "./Notification.vue";
import { useViewChannel } from "@uiloos/vue";
import { notificationChannel } from "./notification-service";

// Via useViewChannel we make sure this component re-renders
// whenever the ViewChannel changes.
const notifications = useViewChannel(notificationChannel);

function dismissAll() {
  notifications.value.dismissAll(undefined);
}
</script>

<style scoped>
.notifications {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 6px 0;
}
</style>
