// react/view-channel/src/ConfirmationDialog/ConfirmationDialog.tsx
import { ConfirmationData } from './types';
import { ViewChannelView } from '@uiloos/core';

type Props = {
  view: ViewChannelView<ConfirmationData, boolean>;
};

export function ConfirmationDialog({ view }: Props) {
  function onOkClicked() {
    view.dismiss(true);
  }

  function onCancelClicked() {
    view.dismiss(false);
  }

  const confirm = view.data;

  return (
    <>
      <div
        className="confirmation-dialog-backdrop"
        onClick={onCancelClicked}
      ></div>

      <div
        className="confirmation-dialog"
        role="dialog"
        aria-label="Please confirm"
        aria-describedby="confirm-text"
      >
        <strong>Please confirm</strong>
        <p id="confirm-text">{confirm.text}</p>

        <div className="confirmation-dialog-button-bar">
          <button onClick={onOkClicked}>Ok</button>
          <button onClick={onCancelClicked}>Cancel</button>
        </div>
      </div>
    </>
  );
}

// angular/view-channel/src/app/examples/confirmation-dialog/confirmation-dialog/confirmation-dialog.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { ConfirmationData } from '../types';

@Component({
  selector: 'confirmation-dialog',
  templateUrl: './confirmation-dialog.component.html',
  styleUrls: ['./confirmation-dialog.component.css'],
  standalone: true
})
export class ConfirmationDialogComponent {
  @Input() view!: ViewChannelView<ConfirmationData, boolean>;

  onOkClicked() {
    this.view.dismiss(true);
  }

  onCancelClicked() {
    this.view.dismiss(false);
  }
}

<div class="confirmation-dialog-backdrop" (click)="onCancelClicked()"></div>

<div
  class="confirmation-dialog"
  role="dialog"
  aria-label="Please confirm"
  [attr.aria-describedby]="view.data.text"
>
  <strong>Please confirm</strong>
  <p>{{ view.data.text }}</p>

  <div class="confirmation-dialog-button-bar">
    <button (click)="onOkClicked()">Ok</button>
    <button (click)="onCancelClicked()">Cancel</button>
  </div>
</div>
