// react/view-channel/src/FlashMessages/FlashMessageViewChannel.tsx
import { useViewChannel } from "@uiloos/react";
import { flashMessageChannel } from "./flash-message-service";
import { FlashMessage } from "./FlashMessage";
import { TransitionGroup } from "react-transition-group";

import "./flash-messages.css";

export function FlashMessageViewChannel() {
  // Via useViewChannel we make sure this component re-renders
  // whenever the ViewChannel changes.
  const flashMessages = useViewChannel(flashMessageChannel);

  return (
    <div className="flash-messages">
      <div
        className="flash-messages-container"
        role="status"
        aria-live="polite"
      >
        <TransitionGroup>
          {flashMessages.views.map((view) => (
            <FlashMessage key={view.data.id} view={view} />
          ))}
        </TransitionGroup>
      </div>
    </div>
  );
}

// svelte/view-channel/src/routes/components/flash-message/FlashMessageViewChannel.svelte
<div role="status" aria-live="polite">
  {#each $flashMessages.views as view}
    <FlashMessage view={view} />
  {/each}
</div>

<script lang="ts">
import FlashMessage from "./FlashMessage.svelte";
import { createViewChannelStore } from "@uiloos/svelte";
import { flashMessageChannel } from "./flash-message-service";

const flashMessages = createViewChannelStore(flashMessageChannel);
</script>
