// vue/view-channel/src/components/confirm-dialog/ConfirmationDialogViewChannel.vue

<template>
  <ConfirmationDialog
    v-for="view in confirmations.views"
    :key="view.data.id"
    :view="view"
  />
</template>

<script lang="ts" setup>
import ConfirmationDialog from "./ConfirmationDialog.vue";
import { useViewChannel } from "@uiloos/vue";
import { confirmationDialogChannel } from "./confirm-dialog-service";

const confirmations = useViewChannel(confirmationDialogChannel);
</script>

// svelte/view-channel/src/routes/components/confirm-dialog/ConfirmationDialogViewChannel.svelte
{#each $confirmations.views as view }
  <ConfirmationDialog view={view} />
{/each}


<script lang="ts">
import ConfirmationDialog from "./ConfirmationDialog.svelte";
import { createViewChannelStore } from "@uiloos/svelte";
import { confirmationDialogChannel } from "./confirm-dialog-service";

const confirmations = createViewChannelStore(confirmationDialogChannel);
</script>
