// react/active-list/src/examples/SegmentedButton/SegmentedButton.tsx
import "./SegmentedButton.css";
import { useActiveList } from "@uiloos/react";
import { SegmentedButtonItem } from "./types";
import classNames from "classnames";

type Props = {
  buttons: SegmentedButtonItem[];
};

export function SegmentedButton({ buttons }: Props) {
  const segmentedButton = useActiveList({
    contents: buttons,
    active: buttons.find((button) => button.active),
  });

  return (
    <div className="segment-container">
      {segmentedButton.contents.map((content) => (
        <button
          key={content.index}
          onClick={(event) => {
            content.activate();
            content.value.onClick(event);
          }}
          className={classNames({ active: content.isActive })}
        >
          {content.value.label}
        </button>
      ))}
    </div>
  );
}

// vue/active-list/src/examples/SegmentedButton/SegmentedButton.vue
<template>
  <div class="segment-container">
    <button
      v-for="content in segmentedButtons.contents"
      :key="content.value.label"
      @click="activate($event, content)"
      :class="{ active: content.isActive }"
    >
      {{ content.value.label }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { ActiveListContent } from "@uiloos/core";
import { useActiveList } from "@uiloos/vue";
import type { SegmentedButtonItem } from "./types.ts";

interface Props {
  buttons: SegmentedButtonItem[];
}

const props = defineProps<Props>();

const segmentedButtons = useActiveList({
  contents: props.buttons,
  active: props.buttons.find((button) => button.active),
});

function activate(
  event: MouseEvent,
  content: ActiveListContent<SegmentedButtonItem>,
) {
  content.activate();
  content.value.onClick(event);
}
</script>

<style>
.segment-container {
  display: flex;
  justify-content: center;
}

.segment-container button {
  color: black;
  padding: 8px;
  font-size: 1.2rem;
}

.segment-container button.active,
.segment-container button:hover {
  color: white;
  background-color: black;
}
</style>
