// svelte/date-gallery/src/examples/Datepicker/MonthSelect.svelte
<select
  value={dateGallery.firstFrame.anchorDate.getMonth()}
  on:change={onMonthChanged}
>
  {#each [...Array(12).keys()] as month (month)}
    <option value={month}>
      {monthFormatter.format(new Date(2000, month, 1))}
    </option>
  {/each}
</select>

<script lang="ts">
  import type { DateGallery } from "@uiloos/core";
  import { monthFormatter } from "../formatters";

  export let dateGallery: DateGallery<unknown>;
    
  function onMonthChanged(e: Event) {
    if (e.target instanceof HTMLSelectElement) {      
      const month = parseInt(e.target.value, 10);

      const date = new Date(dateGallery.firstFrame.anchorDate);
      date.setMonth(month);

      dateGallery.changeConfig({ initialDate: date });
    }
  }
</script>

<style>
  select {
     font-size: 16px;
  }
</style>

// angular/date-gallery/src/app/examples/datepicker/month-select/month-select.component.ts
import { Component, Input } from '@angular/core';
import { DateGallery } from '@uiloos/core';
import { monthFormatter } from '../../formatters';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'month-select',
  templateUrl: './month-select.component.html',
  styleUrls: ['./month-select.component.css'],
  imports: [CommonModule],
  standalone: true,
})
export class MonthSelectComponent {
  @Input() dateGallery!: DateGallery<unknown>;

  public months = [...Array<number>(12).keys()];

  onMonthChanged(e: Event) {
    if (e.target instanceof HTMLSelectElement) {
      const newMonth = parseInt(e.target.value, 10);

      const date = new Date(this.dateGallery.firstFrame.anchorDate);
      date.setMonth(newMonth);

      this.dateGallery.changeConfig({ initialDate: date });
    }
  }

  formatMonth(month: number) {
    return monthFormatter.format(new Date(2000, month, 1));
  }
}

  <select [value]="dateGallery.firstFrame.anchorDate.getMonth()" (change)="onMonthChanged($event)">
    <option *ngFor="let month of months" [value]="month">
      {{ formatMonth(month) }}
    </option>
  </select>
