// svelte/active-list/src/examples/PeekAheadCarousel/Progress.svelte
<script lang="ts">
  import type { ActiveListAutoPlay } from '@uiloos/core';

  export let autoPlay: ActiveListAutoPlay;
  export let hide: boolean;
  let progressElement: HTMLDivElement;

  $: onDurationChanged(autoPlay.duration, progressElement);
  $: onPlayingChanged(autoPlay.isPlaying, progressElement);

  function onDurationChanged(
    duration: number,
    progressElement: HTMLDivElement
  ) {
    if (progressElement) {
      progressElement.style.animation = `progress ${duration}ms linear`;
    }
  }

  function onPlayingChanged(isPlaying: boolean, progressElement: HTMLDivElement) {
    if (progressElement) {
      if (isPlaying) {
        progressElement.style.animationPlayState = 'running';
      } else {
        progressElement.style.animationPlayState = 'paused';
      }
    }
  }
</script>

<div
  bind:this={progressElement}
  class="peek-ahead-carousel-progress"
  class:white={hide}
></div>

<style>
  .peek-ahead-carousel-progress {
    margin-bottom: 4px;
    width: 512px;
    height: 8px;
    background: linear-gradient(
      to right,
      rgb(107 33 168) 50%,
      rgb(102, 102, 102) 50%
    );
    background-size: 200% 100%;
  }

  .peek-ahead-carousel-progress.white {
    background: white;
  }

  @keyframes progress {
    from {
      background-position: right bottom;
    }
    to {
      background-position: left bottom;
    }
  }
</style>

// vue/active-list/src/examples/PeekAheadCarousel/Progress.vue
<template>
  <div
    ref="progressElement"
    class="peek-ahead-carousel-progress"
    :class="{ white: hide }"
  ></div>
</template>

<script setup lang="ts">
import { ref, watchEffect } from "vue";

interface Props {
  duration: number;
  isPlaying: boolean;
  hide: boolean;
}

const props = defineProps<Props>();

const progressElement = ref<HTMLDivElement | null>(null);

// Activate the animation
watchEffect(() => {
  if (progressElement.value) {
    progressElement.value.style.animation = `progress ${props.duration}ms linear`;
  }
});

// Trigger progress animation based on isPlaying state
watchEffect(() => {
  if (progressElement.value) {
    if (props.isPlaying) {
      progressElement.value.style.animationPlayState = "running";
    } else {
      progressElement.value.style.animationPlayState = "paused";
    }
  }
});
</script>

<style>
.peek-ahead-carousel-progress {
  margin-bottom: 4px;
  width: 512px;
  height: 8px;
  background: linear-gradient(
    to right,
    rgb(107 33 168) 50%,
    rgb(102, 102, 102) 50%
  );
  background-size: 200% 100%;
}

.peek-ahead-carousel-progress.white {
  background: white;
}

@keyframes progress {
  from {
    background-position: right bottom;
  }
  to {
    background-position: left bottom;
  }
}
</style>
