// angular/view-channel/src/app/examples/notification/notification/notification.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { NotificationData } from '../types';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'notification',
  templateUrl: './notification.component.html',
  styleUrls: ['./notification.component.css'],
  standalone: true,
  imports: [
    CommonModule
  ]
})
export class NotificationComponent {
  @Input() view!: ViewChannelView<NotificationData, undefined>;

  onClearClicked() {
    this.view.dismiss(undefined);
  }
}

<div class="notification">
  {{ view.data.text }}

  <div class="notification-buttons">
    <button (click)="onClearClicked()" class="notification-button">
      Clear
    </button>

    <button
      *ngFor="let btn of view.data.buttons"
      (click)="btn.onClick($event, view)"
      class="notification-button"
    >
      {{btn.label}}
    </button>
  </div>
</div>

// react/view-channel/src/Notification/Notification.tsx
import { ViewChannelView } from '@uiloos/core';
import { NotificationData } from './types';

import './notification.css';

type Props = {
  view: ViewChannelView<NotificationData, undefined>;
};

export function Notification({ view }: Props) {
  const notification = view.data;

  return (
    <div className="notification">
      {notification.text}

      <div className="notification-buttons">
        <button
          onClick={(event) => view.dismiss(undefined)}
          className="notification-button"
        >
          Clear
        </button>
        {notification.buttons.map((btn, index) => (
          <button
            key={index}
            onClick={(event) => btn.onClick(event, view)}
            className="notification-button"
          >
            {btn.label}
          </button>
        ))}
      </div>
    </div>
  );
}
