// angular/view-channel/src/app/examples/notification/notification-view-channel/notification-view-channel.component.ts
import { Component } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { NotificationService } from '../notification.service';
import { NotificationData } from '../types';
import { NotificationComponent } from '../notification/notification.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'notification-view-channel',
  templateUrl: './notification-view-channel.component.html',
  styleUrls: ['./notification-view-channel.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    NotificationComponent
  ]
})
export class NotificationViewChannelComponent {
  private notificationService: NotificationService;
  public views: ViewChannelView<NotificationData, undefined>[];

  constructor(notificationService: NotificationService) {
    this.notificationService = notificationService;
    this.views = notificationService.notificationChannel.views;
  }

  dismissAll() {
    this.notificationService.notificationChannel.dismissAll(undefined);
  }
}

<div class="notifications">
  <div *ngIf="views.length; else noNotifications">
    <button (click)="dismissAll()">
      Clear all
    </button>
  </div>

  <ng-template #noNotifications>
    <p>No notifications yet</p>
  </ng-template>

  <div role="status" aria-live="polite">
    <notification *ngFor="let view of views" [view]="view"></notification>
  </div>
</div>

// react/view-channel/src/Notification/NotificationViewChannel.tsx
import { useViewChannel } from '@uiloos/react';
import { notificationChannel } from './notification-service';
import { Notification } from './Notification';

export function NotificationViewChannel() {
  // Via useViewChannel we make sure this component re-renders
  // whenever the ViewChannel changes.
  const notifications = useViewChannel(notificationChannel);

  return (
    <div className="notifications">
      {notifications.views.length ? (
        <button onClick={() => notifications.dismissAll(undefined)}>
          Clear all
        </button>
      ) : (
        <p>No notifications yet</p>
      )}

      <div role="status" aria-live="polite">
        {notifications.views.map((view) => (
          <Notification key={view.data.id} view={view} />
        ))}
      </div>
    </div>
  );
}
