// vue/view-channel/src/components/confirm-dialog/ConfirmationDialogViewChannel.vue

<template>
  <ConfirmationDialog
    v-for="view in confirmations.views"
    :key="view.data.id"
    :view="view"
  />
</template>

<script lang="ts" setup>
import ConfirmationDialog from "./ConfirmationDialog.vue";
import { useViewChannel } from "@uiloos/vue";
import { confirmationDialogChannel } from "./confirm-dialog-service";

const confirmations = useViewChannel(confirmationDialogChannel);
</script>

// react/view-channel/src/ConfirmationDialog/ConfirmationDialogViewChannel.tsx
import { useViewChannel } from '@uiloos/react';
import { confirmationDialogChannel } from './confirmation-service';
import { ConfirmationDialog } from './ConfirmationDialog';

import './confirmation-dialog.css';

export function ConfirmationDialogViewChannel() {
  // Via useViewChannel we make sure this component re-renders
  // whenever the ViewChannel changes.
  const confirmations = useViewChannel(confirmationDialogChannel);

  if (confirmations.views.length === 0) {
    return null;
  }

  return (
    <>
      {confirmations.views.map((view) => (
        <ConfirmationDialog key={view.data.id} view={view} />
      ))}
    </>
  );
}
