// react/view-channel/src/FlashMessages/FlashMessage.tsx
import { FlashMessageData } from './types';
import { ViewChannelView } from '@uiloos/core';
import { typeToSymbol } from './utils';
import { CSSTransition } from 'react-transition-group';
import { FlashMessageProgressBar } from './FlashMessageProgressBar';
import { useRef } from 'react';

const ANIMATION_DURATION = 200;

type Props = {
  view: ViewChannelView<FlashMessageData, void>;
};

export function FlashMessage({ view }: Props) {
  const ref = useRef(null);

  // Make sure the CSS and JavaScript are always using
  // the same animation duration, so they cannot go
  // out of sync.
  document.documentElement.style.setProperty(
    '--flash-message-animation-duration',
    `${ANIMATION_DURATION}ms`
  );

  const flashMessage = view.data;

  // Give more important messages a higher CSS z-index,
  // so they slide underneath each other. The expression
  // below inverts the index, for example if the length
  // of the views is 5:
  //
  // 5 - 0 = 5
  // 5 - 1 = 4
  // 5 - 2 = 3
  // 5 - 3 = 2
  // 5 - 4 = 1
  const zIndex = view.viewChannel.views.length - view.index;

  return (
    <CSSTransition
      nodeRef={ref}
      in={view.isPresented}
      timeout={ANIMATION_DURATION}
      classNames="flash-message"
      unmountOnExit
    >
      <div
        ref={ref}
        className={`flash-message flash-message-${flashMessage.type}`}
        style={{ zIndex }}
        onClick={() => view.dismiss()}
        onMouseOver={() => view.pause()}
        onMouseLeave={() => view.play()}
      >
        <div className="flash-message-row">
          <div className="flash-message-content">
            <span className="flash-message-icon">
              {typeToSymbol(flashMessage.type)}
            </span>
            <p>{flashMessage.text}</p>
          </div>
          <span className="flash-message-close">𐄂</span>
        </div>

        <FlashMessageProgressBar view={view} />
      </div>
    </CSSTransition>
  );
}

// angular/view-channel/src/app/examples/flash-messages/flash-message/flash-message.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { FlashMessageData } from '../types';
import { FlashMessageProgressComponent } from '../flash-message-progress/flash-message-progress.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'flash-message',
  templateUrl: './flash-message.component.html',
  styleUrls: ['./flash-message.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    FlashMessageProgressComponent
  ]
})
export class FlashMessageComponent {
  @Input() view!: ViewChannelView<FlashMessageData, undefined>;

  getZIndex() {
    return this.view.viewChannel.views.length - this.view.index;
  }

  getSymbol(): string {
    switch (this.view.data.type) {
      case 'info':
        return 'ⓘ';

      case 'warning':
        return '⚠';

      case 'error':
        return '☠';

      case 'success':
        return '✓';
    }
  }
}

<div
  [ngClass]="['flash-message', 'flash-message-' + view.data.type]"
  [style.zIndex]="getZIndex()"
  (click)="view.dismiss(undefined)"
  (mouseover)="view.pause()"
  (mouseleave)="view.play()"
>
  <div class="flash-message-row">
    <div class="flash-message-content">
      <span class="flash-message-icon">
        {{ getSymbol() }}
      </span>
      <p>{{ view.data.text }}</p>
    </div>
    <span class="flash-message-close">𐄂</span>
  </div>

  <flash-message-progress
    [isPlaying]="view.autoDismiss.isPlaying"
    [duration]="view.autoDismiss.duration"
    [type]="view.data.type"
  ></flash-message-progress>
</div>
