// angular/active-list/src/app/examples/segmented-button/segmented-button.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { SegmentedButtonItem } from './types';
import { ActiveList, ActiveListContent } from '@uiloos/core';

@Component({
  selector: 'segmented-button',
  templateUrl: './segmented-button.component.html',
  styleUrls: ['./segmented-button.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class SegmentedButtonComponent implements OnInit {
  @Input() buttons!: SegmentedButtonItem[];

  public segmentedButtons!: ActiveList<SegmentedButtonItem>;

  ngOnInit(): void {
    this.segmentedButtons = new ActiveList<SegmentedButtonItem>({
      contents: this.buttons,
      active: this.buttons.find((button) => button.active),
    });
  }

  public activate(
    event: MouseEvent,
    content: ActiveListContent<SegmentedButtonItem>,
  ) {
    content.activate();
    content.value.onClick(event);
  }
}

<div class="segment-container">
  <button
    *ngFor="let content of segmentedButtons.contents"
    (click)="activate($event, content)"
    [ngClass]="{ active: content.isActive }"
  >
    {{ content.value.label }}
  </button>
</div>

// react/active-list/src/examples/SegmentedButton/SegmentedButton.tsx
import "./SegmentedButton.css";
import { useActiveList } from "@uiloos/react";
import { SegmentedButtonItem } from "./types";
import classNames from "classnames";

type Props = {
  buttons: SegmentedButtonItem[];
};

export function SegmentedButton({ buttons }: Props) {
  const segmentedButton = useActiveList({
    contents: buttons,
    active: buttons.find((button) => button.active),
  });

  return (
    <div className="segment-container">
      {segmentedButton.contents.map((content) => (
        <button
          key={content.index}
          onClick={(event) => {
            content.activate();
            content.value.onClick(event);
          }}
          className={classNames({ active: content.isActive })}
        >
          {content.value.label}
        </button>
      ))}
    </div>
  );
}
