// angular/active-list/src/app/examples/segmented-button/segmented-button-example.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { SegmentedButtonComponent } from './segmented-button.component';
import { SegmentedButtonItem } from './types';

type TextAlign = 'left' | 'center' | 'right';

@Component({
  selector: 'segmented-button-example',
  templateUrl: './segmented-button-example.component.html',
  styleUrl: './segmented-button-example.component.css',
  standalone: true,
  imports: [CommonModule, SegmentedButtonComponent],
})
export class SegmentedButtonExampleComponent {
  public textAlign: TextAlign = 'center';

  public buttons: SegmentedButtonItem[] = [
    {
      label: 'Left',
      onClick: () => {
        this.textAlign = 'left';
      },
    },
    {
      label: 'Center',
      onClick: () => {
        this.textAlign = 'center';
      },
      active: true,
    },
    {
      label: 'Right',
      onClick: () => {
        this.textAlign = 'right';
      },
    },
  ];
}

<div class="segment-example">
  <segmented-button [buttons]="buttons" />

  <p [ngStyle]="{ textAlign }">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga commodi
    tenetur dignissimos maxime reprehenderit quam hic, molestiae nisi dolorem
    nihil dolor illum asperiores incidunt distinctio quod modi, corporis quae
    neque!
  </p>
</div>
<div class="description">
  <p>
    A segmented button only allows one item to be active at the same time, which
    is a perfect usecase for the ActiveList.
  </p>
</div>

// react/active-list/src/examples/SegmentedButton/SegmentedButtonExample.tsx
import { useState } from "react";
import { SegmentedButton } from "./SegmentedButton";

export function SegmentedButtonExample() {
  // State for the SegmentedButton example
  const [textAlign, setTextAlign] = useState<"left" | "center" | "right">(
    "center",
  );

  return (
    <>
      <div className="segment-example">
        <SegmentedButton
          buttons={[
            {
              label: "Left",
              onClick() {
                setTextAlign("left");
              },
            },
            {
              label: "Center",
              onClick() {
                setTextAlign("center");
              },
              active: true,
            },
            {
              label: "Right",
              onClick() {
                setTextAlign("right");
              },
            },
          ]}
        />

        <p style={{ textAlign }}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga commodi
          tenetur dignissimos maxime reprehenderit quam hic, molestiae nisi
          dolorem nihil dolor illum asperiores incidunt distinctio quod modi,
          corporis quae neque!
        </p>
      </div>
      <div className="description">
        <p>
          A segmented button only allows one item to be active at the same time,
          which is a perfect usecase for the ActiveList.
        </p>
      </div>
    </>
  );
}
