// angular/view-channel/src/app/examples/flash-messages/flash-message/flash-message.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { FlashMessageData } from '../types';
import { FlashMessageProgressComponent } from '../flash-message-progress/flash-message-progress.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'flash-message',
  templateUrl: './flash-message.component.html',
  styleUrls: ['./flash-message.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    FlashMessageProgressComponent
  ]
})
export class FlashMessageComponent {
  @Input() view!: ViewChannelView<FlashMessageData, undefined>;

  getZIndex() {
    return this.view.viewChannel.views.length - this.view.index;
  }

  getSymbol(): string {
    switch (this.view.data.type) {
      case 'info':
        return 'ⓘ';

      case 'warning':
        return '⚠';

      case 'error':
        return '☠';

      case 'success':
        return '✓';
    }
  }
}

<div
  [ngClass]="['flash-message', 'flash-message-' + view.data.type]"
  [style.zIndex]="getZIndex()"
  (click)="view.dismiss(undefined)"
  (mouseover)="view.pause()"
  (mouseleave)="view.play()"
>
  <div class="flash-message-row">
    <div class="flash-message-content">
      <span class="flash-message-icon">
        {{ getSymbol() }}
      </span>
      <p>{{ view.data.text }}</p>
    </div>
    <span class="flash-message-close">𐄂</span>
  </div>

  <flash-message-progress
    [isPlaying]="view.autoDismiss.isPlaying"
    [duration]="view.autoDismiss.duration"
    [type]="view.data.type"
  ></flash-message-progress>
</div>

// vue/view-channel/src/components/flash-message/FlashMessage.vue

<template>
  <div
    :class="['flash-message', 'flash-message-' + view.data.type]"
    :style="{
      'z-index': getZIndex(),
    }"
    @click="view.dismiss()"
    @mouseover="view.pause()"
    @mouseleave="view.play()"
  >
    <div class="flash-message-row">
      <div class="flash-message-content">
        <span class="flash-message-icon">
          {{ getSymbol() }}
        </span>
        <p>{{ view.data.text }}</p>
      </div>
      <span class="flash-message-close">𐄂</span>
    </div>

    <FlashMessageProgressBar
      :duration="view.autoDismiss.duration"
      :type="view.data.type"
      :isPlaying="view.autoDismiss.isPlaying"
    />
  </div>
</template>

<script lang="ts" setup>
import { FlashMessageData } from "./types";
import { ViewChannelView } from "@uiloos/core";
import FlashMessageProgressBar from "./FlashMessageProgressBar.vue";

interface Props {
  view: ViewChannelView<FlashMessageData, void>;
}

const { view } = defineProps<Props>();

function getZIndex() {
  return view.viewChannel.views.length - view.index;
}

function getSymbol(): string {
  switch (view.data.type) {
    case "info":
      return "ⓘ";

    case "warning":
      return "⚠";

    case "error":
      return "☠";

    case "success":
      return "✓";
  }

  return "";
}
</script>

<style scoped>
.flash-messages {
  position: fixed;
  width: 100%;
  /* Place the flash messages below the button */
  top: 200px;
}

.flash-messages-container {
  display: grid;
  gap: 16px;
  padding: 0 10px;
}

.flash-message {
  will-change: transform, opacity;

  padding: 8px;

  font-size: 22px;

  cursor: pointer;

  display: flex;
  flex-direction: column;
  justify-content: space-between;

  font-family: sans-serif;
}

.flash-message-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.flash-message-info {
  color: white;
  background-color: #3b82f6;
}

.flash-message-warning {
  color: white;
  background-color: #eab308;
}

.flash-message-error {
  color: white;
  background-color: #ef4444;
}

.flash-message-success {
  color: white;
  background-color: #22c55e;
}

.flash-message-content {
  display: flex;
  align-items: center;
  gap: 8px;
}

.flash-message-icon {
  font-size: 38px;
}

.flash-message-close {
  font-size: 32px;
  margin-right: 32px;
  margin-top: -5px;
}
</style>
