// angular/date-gallery/src/app/examples/calendar/month-calendar/month-calendar-title.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { DateGallery } from '@uiloos/core';
import { EventData } from '../events';
import { monthAndYearFormatter } from '../../formatters';

@Component({
  selector: 'month-calendar-title',
  template: ` {{ format() }} `,
  standalone: true,
  imports: [CommonModule],
})
export class MonthCalendarTitleComponent {
  @Input() dateGallery!: DateGallery<EventData>;

  format() {
    return monthAndYearFormatter.format(this.dateGallery.firstFrame.anchorDate);
  }
}

// svelte/date-gallery/src/examples/Calendar/MonthCalendar/MonthCalendarTitle.svelte
{monthAndYearFormatter.format(dateGallery.firstFrame.anchorDate)}

<script lang="ts">
  import type { DateGallery } from "@uiloos/core";
  import { monthAndYearFormatter } from "../../formatters";
  import type { EventData } from "../events";

  export let dateGallery: DateGallery<EventData>;
</script>
