// vue/view-channel/src/components/modal/ModalViewChannel.vue

<template>
  <ModalWrapper v-for="view in modals.views" :key="view.data.id" :view="view" />
</template>

<script lang="ts" setup>
import ModalWrapper from "./ModalWrapper.vue";
import { useViewChannel } from "@uiloos/vue";
import { modalChannel } from "./modal-service";

const modals = useViewChannel(modalChannel);
</script>

// svelte/view-channel/src/routes/components/modal/ModalViewChannel.svelte

{#each $modals.views as view}
  <ModalWrapper view={view} />
{/each}

<script lang="ts">
import ModalWrapper from "./ModalWrapper.svelte";
import { createViewChannelStore } from "@uiloos/svelte";
import { modalChannel } from "./modal-service";

const modals = createViewChannelStore(modalChannel);
</script>
