// angular/active-list/src/app/examples/accordion/accordion.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { AccordionItem } from './types';
import { ActiveList, ActiveListContent } from '@uiloos/core';

@Component({
  selector: 'accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class AccordionComponent implements OnInit {
  @Input() items!: AccordionItem[];
  @Input() activeId!: number;

  public accordion!: ActiveList<AccordionItem>;

  ngOnInit(): void {
    this.accordion = new ActiveList<AccordionItem>({
      contents: this.items,
      active:
        this.items.find((item) => item.id === this.activeId) ?? this.items[0],
    });
  }

  // Prevent default opening of details element, // and let the ActiveList
  public open(event: MouseEvent, content: ActiveListContent<AccordionItem>) {
    event.preventDefault();
    content.activate();
  }
}

<div class="accordion-example">
    <details
        *ngFor="let content of accordion.contents"
        [open]="content.isActive"
        (click)="open($event, content)"
    >
        <summary>{{ content.value.summary }}</summary>

        <p>{{ content.value.content }}</p>
    </details>
</div>

// react/active-list/src/examples/Accordion/Accordion.tsx
import "./Accordion.css";
import { useActiveList } from "@uiloos/react";
import { AccordionItem } from "./types";

type Props = {
  items: AccordionItem[];
  activeId?: number | string;
};

export function Accordion({ items, activeId }: Props) {
  const accordion = useActiveList({
    contents: items,
    active: items.find((item) => item.id === activeId) ?? items[0],
  });

  return (
    <div className="accordion-example">
      {accordion.contents.map((content) => (
        <details
          key={content.value.id}
          open={content.isActive}
          onClick={(event) => {
            // Prevent default opening of details element,
            // and let the ActiveList handle this.
            event.preventDefault();

            content.activate();
          }}
        >
          <summary>{content.value.summary}</summary>

          <p>{content.value.content}</p>
        </details>
      ))}
    </div>
  );
}
