// vue/date-gallery/src/examples/DateRangePicker/DateRangePicker.vue
<template>
  <div class="daterangepicker">
    <label>
      {{ startLabel }}:
      <Datepicker
        v-model="startModel"
        @validityChanged="(value: boolean) => onStartValidityChanged(value)"
        :timeEnabled="timeEnabled"
        :label="startErrorLabel"
        :min="min"
        :max="max"
        :required="required"
        :custom-dialog="true"
        @open-dialog="
          () => {
            showDialog = true;
          }
        "
        :linkedPicker="{
          label: endErrorLabel,
          value: endModel ?? '',
          myPosition: 'start',
        }"
      />
    </label>

    <label>
      {{ endLabel }}:
      <Datepicker
        v-model="endModel"
        @validityChanged="(value: boolean) => onEndValidityChanged(value)"
        :timeEnabled="timeEnabled"
        :label="endErrorLabel"
        :min="min"
        :max="max"
        :required="required"
        :custom-dialog="true"
        @open-dialog="
          () => {
            showDialog = true;
          }
        "
        :linkedPicker="{
          label: startErrorLabel,
          value: startModel ?? '',
          myPosition: 'end',
        }"
      />
    </label>

    <DateRangePickerDialog
      v-if="showDialog"
      :startDate="startModel ?? ''"
      :endDate="endModel ?? ''"
      @change="(start: string, end: string) => rangeChanged(start, end)"
      @close="
        () => {
          showDialog = false;
        }
      "
      :min="minDate ?? undefined"
      :max="maxDate ?? undefined"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Datepicker from "../Datepicker/Datepicker.vue";
import DateRangePickerDialog from "./DateRangePickerDialog.vue";
import { parseAsDate } from "../Datepicker/utils";
import { timeFormatter } from "../formatters";
import { isValid } from "date-fns";

type Props = {
  startLabel?: string;
  startErrorLabel?: string;

  endLabel?: string;
  endErrorLabel?: string;

  required?: boolean;
  min?: string;
  max?: string;

  timeEnabled?: boolean;
};

const startModel = defineModel<string>("start");
const endModel = defineModel<string>("end");

const emit = defineEmits<{
  (e: "validityChanged", value: boolean): void;
}>();

const props = withDefaults(defineProps<Props>(), {
  endLabel: "End",
  endErrorLabel: "End",

  startLabel: "Start",
  startErrorLabel: "Start",
});

let showDialog = ref(false);
let startDateIsValid = ref(true);
let endDateIsValid = ref(true);
let minDate = parseAsDate(props.min);
let maxDate = parseAsDate(props.max);

function onStartValidityChanged(valid: boolean) {
  startDateIsValid.value = valid;

  emit("validityChanged", startDateIsValid.value && endDateIsValid.value);
}

function onEndValidityChanged(valid: boolean) {
  endDateIsValid.value = valid;

  emit("validityChanged", startDateIsValid.value && endDateIsValid.value);
}

function rangeChanged(start: string, end: string) {
  if (props.timeEnabled) {
    const startTime = getTimeOfDate(startModel.value ?? "");
    const endTime = getTimeOfDate(endModel.value ?? "");

    startModel.value = `${start} ${startTime}`;
    endModel.value = `${end} ${endTime}`;
  } else {
    startModel.value = start;
    endModel.value = end;
  }
}

function getTimeOfDate(date: string) {
  let time = parseAsDate(date);

  if (isValid(time)) {
    return timeFormatter.format(time as Date);
  } else {
    return "00:00";
  }
}
</script>

<style scoped>
.daterangepicker {
  display: grid;
  gap: 4px;
}

.daterangepicker .calendar-button {
  background-color: white;
  font-size: 16px;
  cursor: pointer;
}

button {
  cursor: pointer;
}
</style>

// svelte/date-gallery/src/examples/DateRangePicker/DateRangePicker.svelte
<div class="daterangepicker">
  <label>
    {startLabel}:
    <Datepicker
      value={startValue}
      timeEnabled={timeEnabled}
      label={startErrorLabel}
      onChange={onStartChanged}
      min={min}
      max={max}
      required={required}
      onValidityChanged={onStartValidityChanged}
       onOpenDialog={() => {
        showDialog = true;
      }}
      linkedPicker={{
        label: endErrorLabel,
        value: endValue,
        myPosition: "start",
      }}
    />
  </label>

  <label>
    {endLabel}:
    <Datepicker
      value={endValue}
      timeEnabled={timeEnabled}
      label={endErrorLabel}
      onChange={onEndChanged}
      min={min}
      max={max}
      required={required}
      onValidityChanged={onEndValidityChanged}
      onOpenDialog={() => {
        showDialog = true;
      }}
      linkedPicker={{
        label: startErrorLabel,
        value: startValue,
        myPosition: "end",
      }}
    />
  </label>

 {#if showDialog}
    <DateRangePickerDialog
      startDate={startValue}
      endDate={endValue}
      onChange={rangeChanged}
      onClose={() => {
        showDialog = false
      }}
      min={minDate ?? undefined}
      max={maxDate ?? undefined}
    />
  {/if}
</div>

<script lang="ts">
  import Datepicker  from "../Datepicker/Datepicker.svelte";
  import  DateRangePickerDialog from "./DateRangePickerDialog.svelte";
  import { parseAsDate } from "../Datepicker/utils";
  import { timeFormatter } from "../formatters";
  import { isValid } from "date-fns";

  export let startValue: string;
  export let onStartChanged: (value: string) => void;
  export let startLabel = "Start";
  export let startErrorLabel = "Start";

  export let endValue: string;
  export let onEndChanged: (value: string) => void;

  export let endLabel = "End";
  export let endErrorLabel = "End";

  export let required: boolean | undefined = undefined;
  export let min: string | undefined = undefined;
  export let max: string | undefined = undefined;

  export let timeEnabled: boolean | undefined = undefined;

  export let validityChanged: (valid: boolean) => void;

  let showDialog = false;
  let startDateIsValid = true;
  let endDateIsValid = true;
  let minDate = parseAsDate(min);
  let maxDate = parseAsDate(max);

  function onStartValidityChanged(valid: boolean) {
    startDateIsValid = valid;

    validityChanged(startDateIsValid && endDateIsValid);
  }

  function onEndValidityChanged(valid: boolean) {
    endDateIsValid = valid;

    validityChanged(startDateIsValid && endDateIsValid);
  }

  function rangeChanged(start: string, end: string) {
    if (timeEnabled) {
      const startTime = getTimeOfDate(startValue);
      const endTime = getTimeOfDate(endValue);

      onStartChanged(`${start} ${startTime}`);
      onEndChanged(`${end} ${endTime}`);
    } else {
      onStartChanged(start);
      onEndChanged(end);
    }
  }

  function getTimeOfDate(date: string) {
    let time = parseAsDate(date);

    if (isValid(time)) {
      return timeFormatter.format(time as Date);
    } else {
      return "00:00";
    }
  }
</script>

<style>
.daterangepicker {
  display: grid;
  gap: 4px;
}
</style>
