// angular/date-gallery/src/app/examples/daterange-picker/daterange-picker.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { isValid } from 'date-fns';
import { timeFormatter } from '../formatters';
import { DatepickerComponent } from '../datepicker/datepicker.component';
import { parseAsDate } from '../datepicker/utils';
import { DaterangePickerDialogComponent } from './daterange-picker-dialog/daterange-picker-dialog.component';

@Component({
  selector: 'daterange-picker',
  templateUrl: './daterange-picker.component.html',
  styleUrls: ['./daterange-picker.component.css'],
  standalone: true,
  imports: [CommonModule, DatepickerComponent, DaterangePickerDialogComponent],
})
export class DaterangePickerComponent {
  @Input() start!: string;
  @Output() startChange = new EventEmitter<string>();

  @Input() end!: string;
  @Output() endChange = new EventEmitter<string>();

  @Input() startLabel = 'Start';
  @Input() startErrorLabel = 'Start';

  @Input() endLabel = 'End';
  @Input() endErrorLabel = 'End';

  @Input() required?: boolean;
  @Input() min?: string;
  @Input() max?: string;

  @Input() timeEnabled?: boolean;

  @Output() validityChanged = new EventEmitter<boolean>();

  public showDialog = false;
  public startDateIsValid = true;
  public endDateIsValid = true;
  public minDate = parseAsDate(this.min);
  public maxDate = parseAsDate(this.max);

  setStart(value: string) {
    this.start = value;

    this.startChange.emit(value);
  }

  setEnd(value: string) {
    this.end = value;

    this.endChange.emit(value);
  }

  onStartValidityChanged(valid: boolean) {
    this.startDateIsValid = valid;

    this.validityChanged.emit(this.startDateIsValid && this.endDateIsValid);
  }

  onEndValidityChanged(valid: boolean) {
    this.endDateIsValid = valid;

    this.validityChanged.emit(this.startDateIsValid && this.endDateIsValid);
  }

  rangeChanged({ start, end }: { start: string; end: string }) {
    if (this.timeEnabled) {
      const startTime = this.getTimeOfDate(this.start ?? '');
      const endTime = this.getTimeOfDate(this.end ?? '');

      this.start = `${start} ${startTime}`;
      this.end = `${end} ${endTime}`;
    } else {
      this.start = start;
      this.end = end;
    }

    this.startChange.emit(this.start);
    this.endChange.emit(this.end);
  }

  getTimeOfDate(date: string) {
    let time = parseAsDate(date);

    if (isValid(time)) {
      return timeFormatter.format(time as Date);
    } else {
      return '00:00';
    }
  }

  openDialog() {
    this.showDialog = true;
  }

  closeDialog() {
    this.showDialog = false;
  }
}

<div class="daterangepicker">
    <label>
      {{ startLabel }}:
      <datepicker
        [value]="start"
        (valueChange)="setStart($event)"
        (validityChanged)="onStartValidityChanged($event)"
        [timeEnabled]="timeEnabled"
        [label]="startErrorLabel"
        [min]="min"
        [max]="max"
        [required]="required"
        (openDialog)="openDialog()"
        [linkedPicker]="{
          label: endErrorLabel,
          value: end,
          myPosition: 'start',
        }"
      />
    </label>

    <label>
      {{ endLabel }}:
      <datepicker
        [value]="end"
        (valueChange)="setEnd($event)"
        (validityChanged)="onEndValidityChanged($event)"
        [timeEnabled]="timeEnabled"
        [label]="endErrorLabel"
        [min]="min"
        [max]="max"
        [required]="required"
        (openDialog)="openDialog()"
        [linkedPicker]="{
          label: startErrorLabel,
          value: start,
          myPosition: 'end',
        }"
      />
    </label>

    <daterange-picker-dialog
      *ngIf="showDialog"
      [startDate]="start"
      [endDate]="end"
      (rangeChanged)="rangeChanged($event)"
      (close)="closeDialog()"
      [min]="minDate ?? undefined"
      [max]="maxDate ?? undefined"
    />
  </div>

// svelte/date-gallery/src/examples/DateRangePicker/DateRangePicker.svelte
<div class="daterangepicker">
  <label>
    {startLabel}:
    <Datepicker
      value={startValue}
      timeEnabled={timeEnabled}
      label={startErrorLabel}
      onChange={onStartChanged}
      min={min}
      max={max}
      required={required}
      onValidityChanged={onStartValidityChanged}
       onOpenDialog={() => {
        showDialog = true;
      }}
      linkedPicker={{
        label: endErrorLabel,
        value: endValue,
        myPosition: "start",
      }}
    />
  </label>

  <label>
    {endLabel}:
    <Datepicker
      value={endValue}
      timeEnabled={timeEnabled}
      label={endErrorLabel}
      onChange={onEndChanged}
      min={min}
      max={max}
      required={required}
      onValidityChanged={onEndValidityChanged}
      onOpenDialog={() => {
        showDialog = true;
      }}
      linkedPicker={{
        label: startErrorLabel,
        value: startValue,
        myPosition: "end",
      }}
    />
  </label>

 {#if showDialog}
    <DateRangePickerDialog
      startDate={startValue}
      endDate={endValue}
      onChange={rangeChanged}
      onClose={() => {
        showDialog = false
      }}
      min={minDate ?? undefined}
      max={maxDate ?? undefined}
    />
  {/if}
</div>

<script lang="ts">
  import Datepicker  from "../Datepicker/Datepicker.svelte";
  import  DateRangePickerDialog from "./DateRangePickerDialog.svelte";
  import { parseAsDate } from "../Datepicker/utils";
  import { timeFormatter } from "../formatters";
  import { isValid } from "date-fns";

  export let startValue: string;
  export let onStartChanged: (value: string) => void;
  export let startLabel = "Start";
  export let startErrorLabel = "Start";

  export let endValue: string;
  export let onEndChanged: (value: string) => void;

  export let endLabel = "End";
  export let endErrorLabel = "End";

  export let required: boolean | undefined = undefined;
  export let min: string | undefined = undefined;
  export let max: string | undefined = undefined;

  export let timeEnabled: boolean | undefined = undefined;

  export let validityChanged: (valid: boolean) => void;

  let showDialog = false;
  let startDateIsValid = true;
  let endDateIsValid = true;
  let minDate = parseAsDate(min);
  let maxDate = parseAsDate(max);

  function onStartValidityChanged(valid: boolean) {
    startDateIsValid = valid;

    validityChanged(startDateIsValid && endDateIsValid);
  }

  function onEndValidityChanged(valid: boolean) {
    endDateIsValid = valid;

    validityChanged(startDateIsValid && endDateIsValid);
  }

  function rangeChanged(start: string, end: string) {
    if (timeEnabled) {
      const startTime = getTimeOfDate(startValue);
      const endTime = getTimeOfDate(endValue);

      onStartChanged(`${start} ${startTime}`);
      onEndChanged(`${end} ${endTime}`);
    } else {
      onStartChanged(start);
      onEndChanged(end);
    }
  }

  function getTimeOfDate(date: string) {
    let time = parseAsDate(date);

    if (isValid(time)) {
      return timeFormatter.format(time as Date);
    } else {
      return "00:00";
    }
  }
</script>

<style>
.daterangepicker {
  display: grid;
  gap: 4px;
}
</style>
