// svelte/date-gallery/src/examples/Calendar/EventForm/EventForm.svelte
<Dialog onClose={onClose}>
  <form class="calendar-event-form" on:submit={onSubmit}>
    <b class="calendar-event-form-title">
      {formEvent ? "Edit event" : "Add event"}
    </b>

    <div class="calendar-event-form-field">
      <label for="title">Title</label>
      <input
        id="title"
        name="title"
        value={title}
        on:change={(e) => {
          if (e.target instanceof HTMLInputElement) {
            title = e.target.value;
          }
        }}
      />
    
      {#if titleError}
        <span class="error">{titleError}</span>
      {/if}
    </div>

    <div class="calendar-event-form-field">
      <label for="description">Description</label>
      <textarea
        id="description"
        name="description"
        cols="4"
        rows="4"
        value={description}
        on:change={(e) => {
          if (e.target instanceof HTMLTextAreaElement) {
            description = e.target.value;
          }
        }}
      ></textarea>
    
      {#if descriptionError}
        <span class="error">{descriptionError}</span>
      {/if}
    </div>

    <DateRangePicker
      timeEnabled
      startValue={startDate}
      onStartChanged={(value) => {
        startDate = value;
      }}
      endValue={endDate}
      onEndChanged={(value) => {
        endDate = value;
      }}
      validityChanged={(value) => {
        rangeValid = value;
      }}
      startLabel="Start (mm/dd/yyyy hh:mm)"
      endLabel="End (mm/dd/yyyy hh:mm)"
      startErrorLabel="Start"
      endErrorLabel="End"
      required
    />

    <div class="calendar-event-form-field">
      <label for="color">Color</label>
      <input
        id="color"
        name="color"
        type="color"
        value={color}
        on:change={(e) => {
          if (e.target instanceof HTMLInputElement) {
            color = e.target.value;
          }
        }}
      />

      {#if colorError}
        <span class="error">{colorError}</span>
      {/if}
    </div>

    <button type="submit">Save</button>
  </form>

  {#if formEvent}
    <button class="delete-event-button" on:click={deleteButtonClicked}>
      Delete event
    </button>
  {/if}
</Dialog>

<script lang="ts">
  import Dialog from '../../Dialog/Dialog.svelte';
  import { DateGallery, DateGalleryEvent } from "@uiloos/core";
  import { eventId, formatDateForInput } from "./../events";
  import type { EventData} from "./../events";
  import DateRangePicker  from "../../DateRangePicker/DateRangePicker.svelte";

  export let dateGallery: DateGallery<EventData>;
  export let formEvent: DateGalleryEvent<EventData> | undefined = undefined;
  export let formDate: Date | undefined = undefined;
  export let onClose: () => void;

  // Please use a good form library such as Superforms or svelte-forms-lib

  let title = formEvent ? formEvent.data.title : "";
  let titleError = "";

  let description = formEvent ? formEvent.data.description : "";
  let descriptionError = "";

  let startDate = '';
  if (formEvent) {
    startDate = formatDateForInput(formEvent.startDate);
  } else if (formDate) {
    startDate = formatDateForInput(formDate);
  } 
  
  let endDate = '';
  if (formEvent) {
    endDate = formatDateForInput(formEvent.endDate);
  } else if (formDate) {
    const date = new Date(formDate);
    date.setHours(formDate.getHours() + 1, formDate.getMinutes());

    endDate = formatDateForInput(date);
  }

  let rangeValid = false;

  let color = formEvent ? formEvent.data.color : "#000000";
  let colorError = "";

  function onSubmit(e: Event) {
    e.preventDefault();

    let valid = true;

    if (title === "") {
      titleError = "Title is required";
      valid = false;
    } else {
      titleError = "";
    }

    if (description === "") {
      descriptionError = "Description is required";
      valid = false;
    } else {
      descriptionError = "";
    }

    if (color === "") {
      colorError = "Color is required";
      valid = false;
    } else {
      colorError = "";
    }

    if (!rangeValid || !valid) {
      return;
    }

    if (formEvent === undefined) {
      // Inform the dateGallery of the new event
      dateGallery.addEvent({
        data: {
          id: eventId(),
          title,
          description,
          color,
        },
        startDate,
        endDate,
      });
    } else {
      // Inform the dateGallery that the event has changed.

      // First update the data object of the event, to whatever
      // the user filled in.
      formEvent.changeData({
        id: formEvent.data.id,
        title,
        description,
        color,
      });

      // Then tell the DateGallery that the event has actually moved
      formEvent.move({
        startDate,
        endDate,
      });
    }

    onClose();
  }

  function deleteButtonClicked() {
    if (formEvent) {
      formEvent.remove();
      onClose();
    }
  }
</script>

<style>
/* The add / edit event forms */

.calendar-event-form {
  display: grid;
  gap: 8px;
  padding: 8px 0px;
}

.calendar-event-form input {
  border: 1px solid black;
  height: 32px;
  padding: 4px;
}

.error {
  color: red;
}

.calendar-event-form textarea {
  border: 1px solid black;
  padding: 4px;
}

.calendar-event-form button[type="submit"] {
  border: 1px solid black;
  height: 32px;
}

.calendar-event-form .calendar-event-form-field {
  display: grid;
  min-height: 32px;
  gap: 4px;
}

.delete-event-button {
  color: white;
  background-color: #dc2626;
  width: 100%;
  height: 32px;
  cursor: pointer;
}

</style>

// react/date-gallery/src/examples/Calendar/EventForm/EventForm.tsx
import { DateGallery, DateGalleryEvent } from "@uiloos/core";
import React, { useState, FormEvent, useRef } from "react";
import { Dialog } from "../../Dialog/Dialog";
import { EventData, eventId, formatDateForInput } from "./../events";
import { DateRangePicker } from "../../DateRangePicker/DateRangePicker";
import "./EventForm.css";

type Props = {
  dateGallery: DateGallery<EventData>;
  formEvent?: DateGalleryEvent<EventData>;
  formDate?: Date;
  onClose(): void;
};

export function EventForm({
  formEvent,
  onClose,
  dateGallery,
  formDate,
}: Props) {
  // Please use a good form library such as Formik, Final Form or react-hook-form
  // instead of this

  const [title, setTitle] = useState(() =>
    formEvent ? formEvent.data.title : "",
  );
  const [titleError, setTitleError] = useState("");

  const [description, setDescription] = useState(() =>
    formEvent ? formEvent.data.description : "",
  );
  const [descripitonError, setDescriptionError] = useState("");

  const [startDate, setStartDate] = useState(() => {
    if (formEvent) {
      return formatDateForInput(formEvent.startDate);
    } else if (formDate) {
      return formatDateForInput(formDate);
    } else {
      return "";
    }
  });
  const [endDate, setEndDate] = useState(() => {
    if (formEvent) {
      return formatDateForInput(formEvent.endDate);
    } else if (formDate) {
      const date = new Date(formDate);
      date.setHours(formDate.getHours() + 1, formDate.getMinutes());

      return formatDateForInput(date);
    } else {
      return "";
    }
  });
  const [rangeValid, setRangeValid] = useState(false);

  const [color, setColor] = useState(() =>
    formEvent ? formEvent.data.color : "#000000",
  );
  const [colorError, setColorError] = useState("");

  function onSubmit(e: FormEvent) {
    e.preventDefault();

    let valid = true;

    if (title === "") {
      setTitleError("Title is required");
      valid = false;
    } else {
      setTitleError("");
    }

    if (description === "") {
      setDescriptionError("Description is required");
      valid = false;
    } else {
      setDescriptionError("");
    }

    if (color === "") {
      setColorError("Color is required");
      valid = false;
    } else {
      setColorError("");
    }

    if (!rangeValid || !valid) {
      return;
    }

    const isCreating = formEvent === undefined;

    if (isCreating) {
      // Inform the dateGallery of the new event
      dateGallery.addEvent({
        data: {
          id: eventId(),
          title,
          description,
          color,
        },
        startDate,
        endDate,
      });
    } else {
      // Inform the dateGallery that the event has changed.

      // First update the data object of the event, to whatever
      // the user filled in.
      formEvent.changeData({
        id: formEvent.data.id,
        title,
        description,
        color,
      });

      // Then tell the DateGallery that the event has actually moved
      formEvent.move({
        startDate,
        endDate,
      });
    }

    onClose();
  }

  function deleteButtonClicked() {
    if (formEvent) {
      formEvent.remove();
      onClose();
    }
  }

  return (
    <Dialog onClose={onClose}>
      <form className="calendar-event-form" onSubmit={onSubmit}>
        <b className="calendar-event-form-title">
          {formEvent ? "Edit event" : "Add event"}
        </b>

        <div className="calendar-event-form-field">
          <label htmlFor="title">Title</label>
          <input
            id="title"
            name="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          {titleError ? <span className="error">{titleError}</span> : null}
        </div>

        <div className="calendar-event-form-field">
          <label htmlFor="description">Description</label>
          <textarea
            id="description"
            name="description"
            cols={4}
            rows={4}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          ></textarea>
          {descripitonError ? (
            <span className="error">{descripitonError}</span>
          ) : null}
        </div>

        <DateRangePicker
          timeEnabled
          startValue={startDate}
          onStartChanged={setStartDate}
          endValue={endDate}
          onEndChanged={setEndDate}
          validityChanged={setRangeValid}
          startLabel="Start (mm/dd/yyyy hh:mm)"
          endLabel="End (mm/dd/yyyy hh:mm)"
          startErrorLabel="Start"
          endErrorLabel="End"
          required
        />

        <div className="calendar-event-form-field">
          <label htmlFor="color">Color</label>
          <input
            id="color"
            name="color"
            type="color"
            value={color}
            onChange={(e) => setColor(e.target.value)}
          />
          {colorError ? <span className="error">{colorError}</span> : null}
        </div>

        <button type="submit">Save</button>
      </form>

      {formEvent ? (
        <button className="delete-event-button" onClick={deleteButtonClicked}>
          Delete event
        </button>
      ) : null}
    </Dialog>
  );
}
