// svelte/view-channel/src/routes/components/example-modals/CarModal.svelte
<ol>
  <li>
    <button on:click={() => onCarClicked('ford')}>Ford</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('audi')}>Audi</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('toyota')}>Toyota</button>
  </li>
</ol>

<script lang="ts">
import type { ModalComponent } from "../modal/types";
import type { ViewChannelView } from "@uiloos/core";

type CarModalResult = "ford" | "audi" | "toyota";

export let view: ViewChannelView<unknown, CarModalResult>;

function onCarClicked(car: CarModalResult) {
  view.dismiss(car);
}
</script>

// vue/view-channel/src/components/example-modals/CarModal.vue
<template>
  <ol>
    <li>
      <button @click="onCarClicked('ford')">Ford</button>
    </li>
    <li>
      <button @click="onCarClicked('audi')">Audi</button>
    </li>
    <li>
      <button @click="onCarClicked('toyota')">Toyota</button>
    </li>
  </ol>
</template>

<script lang="ts" setup>
import { ViewChannelView } from "@uiloos/core";

type CarModalResult = "ford" | "audi" | "toyota";

interface Props {
  view: ViewChannelView<any, CarModalResult>;
  data: {};
}

const { view } = defineProps<Props>();

function onCarClicked(car: CarModalResult) {
  view.dismiss(car);
}
</script>
