// react/view-channel/src/ExampleModals/PokemonModal.tsx
import { ModalComponentProps } from '../Modal/types';

type Props = {
  text: string;
};

type PokemonModalResult = 'bulbasaur' | 'squirtle' | 'charmander';

export function PokemonModal(
  props: ModalComponentProps<Props, PokemonModalResult>
) {
  function onPokemonClicked(pokemon: PokemonModalResult) {
    props.view.dismiss(pokemon);
  }

  return (
    <>
      <p>{props.text}</p>

      <ol>
        <li>
          <button onClick={() => onPokemonClicked('bulbasaur')}>
            Bulbasaur
          </button>
        </li>
        <li>
          <button onClick={() => onPokemonClicked('squirtle')}>Squirtle</button>
        </li>
        <li>
          <button onClick={() => onPokemonClicked('charmander')}>
            Charmander
          </button>
        </li>
      </ol>
    </>
  );
}

// vue/view-channel/src/components/example-modals/PokemonModal.vue
<template>
  <p>{{ data.text }}</p>

  <ol>
    <li>
      <button @click="onPokemonClicked('bulbasaur')">Bulbasaur</button>
    </li>
    <li>
      <button @click="onPokemonClicked('squirtle')">Squirtle</button>
    </li>
    <li>
      <button @click="onPokemonClicked('charmander')">Charmander</button>
    </li>
  </ol>
</template>

<script lang="ts" setup>
import { ModalComponent } from "../modal/types";
import { ViewChannelView } from "@uiloos/core";
import { confirmDialog } from "../confirm-dialog/confirm-dialog-service";

export type PokemonModalResult = "bulbasaur" | "squirtle" | "charmander";

type PokemonModalComponentData = {
  text: string;
};

interface Props {
  view: ViewChannelView<any, PokemonModalResult>;
  data: PokemonModalComponentData;
}

const { view } = defineProps<Props>();

function onPokemonClicked(pokemon: PokemonModalResult) {
  view.dismiss(pokemon);
}
</script>
