// svelte/view-channel/src/routes/components/example-modals/PokemonModal.svelte
<p>{ data.text }</p>

<ol>
  <li>
    <button on:click={() => onPokemonClicked('bulbasaur')}>Bulbasaur</button>
  </li>
  <li>
    <button on:click={() => onPokemonClicked('squirtle')}>Squirtle</button>
  </li>
  <li>
    <button on:click={() => onPokemonClicked('charmander')}>Charmander</button>
  </li>
</ol>

<script lang="ts">
import type { ModalComponent } from "../modal/types";
import type { ViewChannelView } from "@uiloos/core";
import { confirmDialog } from "../confirm-dialog/confirm-dialog-service";

type PokemonModalComponentData = {
  text: string;
};

export let view: ViewChannelView<unknown, PokemonModalResult>;
export let data: PokemonModalComponentData;

function onPokemonClicked(pokemon: PokemonModalResult) {
  view.dismiss(pokemon);
}

</script>

<script context="module" lang="ts">
export type PokemonModalResult = "bulbasaur" | "squirtle" | "charmander";
</script>

// vue/view-channel/src/components/example-modals/PokemonModal.vue
<template>
  <p>{{ data.text }}</p>

  <ol>
    <li>
      <button @click="onPokemonClicked('bulbasaur')">Bulbasaur</button>
    </li>
    <li>
      <button @click="onPokemonClicked('squirtle')">Squirtle</button>
    </li>
    <li>
      <button @click="onPokemonClicked('charmander')">Charmander</button>
    </li>
  </ol>
</template>

<script lang="ts" setup>
import { ModalComponent } from "../modal/types";
import { ViewChannelView } from "@uiloos/core";
import { confirmDialog } from "../confirm-dialog/confirm-dialog-service";

export type PokemonModalResult = "bulbasaur" | "squirtle" | "charmander";

type PokemonModalComponentData = {
  text: string;
};

interface Props {
  view: ViewChannelView<any, PokemonModalResult>;
  data: PokemonModalComponentData;
}

const { view } = defineProps<Props>();

function onPokemonClicked(pokemon: PokemonModalResult) {
  view.dismiss(pokemon);
}
</script>
