// vue/date-gallery/src/Tabs/Tab.vue
<template>
  <div v-if="activeHref === props.href" class="tab-content">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { ActiveList } from "@uiloos/core";
import { inject, ref, unref, Ref } from "vue";
import { activeInjectionKey, tabInjectionKey } from "./util";
import type { TabInfo } from "./types";

interface Props {
  name: string;
  href: string;
}

const props = defineProps<Props>();

const tabs = unref(inject(tabInjectionKey) as ActiveList<TabInfo>);
const activeHref = inject(activeInjectionKey) as Ref<string>;

ref(tabs.push({ ...props }));
</script>

<style scoped>
.tab-content {
  padding: 16px;
}
</style>

// svelte/date-gallery/src/Tabs/Tab.svelte

{#if $activeHref === href}
  <div class="tab-content">
    <slot></slot>
  </div>
{/if}

<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import { TABS, TABS_ACTIVE } from './Tabs.svelte';
  import type {ActiveList} from '@uiloos/core';
  import type {TabInfo} from './types';

  export let name: string;
  export let href: string;

  const tabs: ActiveList<TabInfo> = getContext(TABS);
  const activeHref: SvelteStore<string> = getContext(TABS_ACTIVE);

  onMount(() => {
    tabs.push({ name, href});
  });
</script>

<style>
.tab-content {
  padding: 16px;
}
</style>
