// vue/active-list/src/App.vue
<template>
  <Tabs>
    <Tab name="Snap carousel" href="#snap-carousel">
      <SnapCarousel :slides="owls" />

      <div class="description">
        <p>
          The example above shows a CSS based snap carousel, it has been
          enhanced by "uiloos" to move to the next slide by itself via the
          ActiveList autoPlay feature.
        </p>

        <p>
          When the user interacts with the carousel the autoPlay is disabled and
          the user assumes control of the carousel.
        </p>

        <p>
          When you disabled JavaScript carousel will still work, but it will not
          autoPlay.
        </p>
      </div>
    </Tab>

    <Tab name="Peek carousel" href="#peek-carousel">
      <PeekAheadCarousel :slides="owls" />

      <div class="description">
        <p>
          This is a variant of the "Snap Carousel" example which shows the user
          a little bit of the previous and next slides.
        </p>

        <p>
          When the user interacts with the carousel the autoPlay is disabled and
          the user assumes control of the carousel.
        </p>

        <p>
          When you disabled JavaScript carousel will still work, but it will not
          autoPlay.
        </p>
      </div>
    </Tab>

    <Tab name="Classic carousel" href="#classic-carousel">
      <ClassicCarousel :slides="owls" />

      <div class="description">
        <p>
          This example shows a classic carousel, it is classic because it does
          not use modern CSS (with snap points) to create the carousel.
        </p>

        <p>
          Instead it uses JavaScript to create the carousel, which is why it
          does not work when JavaScript is disabled.
        </p>

        <p>
          The user can either use the chevron buttons to navigate between the
          slides, or the user can click on the progress indicators. Once the
          user takes control of the carousel it will stop auto playing.
        </p>
      </div>
    </Tab>

    <Tab name="Accordion" href="#accordion">
      <AccordionExample />
    </Tab>

    <Tab name="Segmented button" href="#segmented-button">
      <SegmentedButtonExample />
    </Tab>

    <Tab name="Todo list" href="#todo-list">
      <TodoList />

      <div class="description">
        <p>
          This todo example shows that multiple items can be 'active' at the
          same time in the ActiveList.
        </p>

        <p>
          It also demonstrates how easy it is to move items around in the list.
          Try drag and dropping the todos.
        </p>
      </div>
    </Tab>

    <Tab name="Image gallery" href="#image-gallery">
      <Gallery
        :images="
          owls.map((owl) => ({ alt: owl.description, src: owl.img.src }))
        "
      />

      <div class="description">
        <p>
          The gallery is popular on websites that have a lot of images to show,
          but do not want to single out a single image.
        </p>
      </div>
    </Tab>

    <Tab name="Timeline" href="#timeline">
      <TimelineExample />
      <div class="description">
        <p>
          The idea behind this example is to show that "uiloos" is aware of the
          position an item has within the ActiveList. "uiloos" can tell you what
          the next item, previous item and what first and last items are.
        </p>

        <p>
          You can then use this information to set different CSS classes for
          each item.
        </p>
      </div>
    </Tab>

    <Tab name="Selector" href="#selector">
      <CondimentSelectorExample />

      <div class="description">
        <p>
          This example shows that via "maxActivationLimit" you can limit the
          amount of content / items that can be active.
        </p>

        <p>
          By setting "maxActivationLimitBehavior" to "ignore" whenever more
          items are activated than the "maxActivationLimit" they are simply
          ignored.
        </p>
      </div>
    </Tab>
  </Tabs>
</template>

<script setup lang="ts">
import { reactive } from "vue";
import Tabs from "./examples/Tabs/Tabs.vue";
import Tab from "./examples/Tabs/Tab.vue";
import SnapCarousel from "./examples/SnapCarousel/SnapCarousel.vue";
import PeekAheadCarousel from "./examples/PeekAheadCarousel/PeekAheadCarousel.vue";
import ClassicCarousel from "./examples/ClassicCarousel/ClassicCarousel.vue";
import AccordionExample from "./examples/Accordion/AccordionExample.vue";
import SegmentedButtonExample from "./examples/SegmentedButton/SegmentedButtonExample.vue";
import TodoList from "./examples/TodoList/TodoList.vue";
import Gallery from "./examples/Gallery/Gallery.vue";
import TimelineExample from "./examples/Timeline/TimelineExample.vue";
import CondimentSelectorExample from "./examples/Selector/CondimentSelectorExample.vue";

import { owls } from "./owls";
</script>

// react/active-list/src/App.tsx
import "./styles.css";
import { PeekAheadCarousel } from "./examples/PeekAheadCarousel/PeekAheadCarousel";
import { Tabs } from "./examples/Tabs/Tabs";
import { Tab } from "./examples/Tabs/Tab";
import { SnapCarousel } from "./examples/SnapCarousel/SnapCarousel";
import { owls } from "./owls";
import { ClassicCarousel } from "./examples/ClassicCarousel/ClassicCarousel";
import { Gallery } from "./examples/Gallery/Gallery";
import { TodoList } from "./examples/TodoList/TodoList";
import { AccordionExample } from "./examples/Accordion/AccordionExample";
import { SegmentedButtonExample } from "./examples/SegmentedButton/SegmentedButtonExample";
import { CondimentSelectorExample } from "./examples/Selector/CondimentSelectorExample";
import { TimelineExample } from "./examples/Timeline/TimelineExample";

export default function App() {
  return (
    <Tabs>
      <Tab name="Snap carousel" href="#snap-carousel">
        <SnapCarousel slides={owls} />

        <div className="description">
          <p>
            The example above shows a CSS based snap carousel, it has been
            enhanced by "uiloos" to move to the next slide by itself via the
            ActiveList autoPlay feature.
          </p>

          <p>
            When the user interacts with the carousel the autoPlay is disabled
            and the user assumes control of the carousel.
          </p>

          <p>
            When you disabled JavaScript carousel will still work, but it will
            not autoPlay.
          </p>
        </div>
      </Tab>

      <Tab name="Peek carousel" href="#peek-carousel">
        <PeekAheadCarousel slides={owls} />

        <div className="description">
          <p>
            This is a variant of the "Snap Carousel" example which shows the
            user a little bit of the previous and next slides.
          </p>

          <p>
            When the user interacts with the carousel the autoPlay is disabled
            and the user assumes control of the carousel.
          </p>

          <p>
            When you disabled JavaScript carousel will still work, but it will
            not autoPlay.
          </p>
        </div>
      </Tab>

      <Tab name="Classic carousel" href="#classic-carousel">
        <ClassicCarousel slides={owls} />

        <div className="description">
          <p>
            This example shows a classic carousel, it is classic because it does
            not use modern CSS (with snap points) to create the carousel.
          </p>

          <p>
            Instead it uses JavaScript to create the carousel, which is why it
            does not work when JavaScript is disabled.
          </p>

          <p>
            The user can either use the chevron buttons to navigate between the
            slides, or the user can click on the progress indicators. Once the
            user takes control of the carousel it will stop auto playing.
          </p>
        </div>
      </Tab>

      <Tab name="Accordion" href="#accordion">
        <AccordionExample />
      </Tab>

      <Tab name="Segmented button" href="#segmented-button">
        <SegmentedButtonExample />
      </Tab>

      <Tab name="Todo list" href="#todo-list">
        <TodoList />
        <div className="description">
          <p>
            This todo example shows that multiple items can be 'active' at the
            same time in the ActiveList.
          </p>

          <p>
            It also demonstrates how easy it is to move items around in the
            list. Try drag and dropping the todos.
          </p>
        </div>
      </Tab>

      <Tab name="Image gallery" href="#image-gallery">
        <Gallery
          images={owls.map((owl) => ({
            alt: owl.description,
            src: owl.img.src,
          }))}
        />

        <div className="description">
          <p>
            The gallery is popular on websites that have a lot of images to
            show, but do not want to single out a single image.
          </p>
        </div>
      </Tab>

      <Tab name="Timeline" href="#timeline">
        <TimelineExample />
        <div className="description">
          <p>
            The idea behind this example is to show that "uiloos" is aware of
            the position an item has within the ActiveList. "uiloos" can tell
            you what the next item, previous item and what first and last items
            are.
          </p>

          <p>
            You can then use this information to set different CSS classes for
            each item.
          </p>
        </div>
      </Tab>

      <Tab name="Selector" href="#selector">
        <CondimentSelectorExample />

        <div className="description">
          <p>
            This example shows that via "maxActivationLimit" you can limit the
            amount of content / items that can be active.
          </p>

          <p>
            By setting "maxActivationLimitBehavior" to "ignore" whenever more
            items are activated than the "maxActivationLimit" they are simply
            ignored.
          </p>
        </div>
      </Tab>
    </Tabs>
  );
}
