// vue/active-list/src/examples/Tabs/Tab.vue
<template>
  <div v-if="activeHref === props.href" class="tab-content">
    <slot></slot>
  </div>

  
</template>

<script setup lang="ts">
import { ActiveList } from "@uiloos/core";
import { Ref, inject, ref, unref } from "vue";
import { activeInjectionKey, tabInjectionKey } from "./util";
import type { TabInfo } from "./types";

interface Props {
  name: string;
  href: string;
}

const props = defineProps<Props>();

const tabs = unref(inject(tabInjectionKey) as ActiveList<TabInfo>);
const activeHref = inject(activeInjectionKey) as Ref<string>;

ref(tabs.push({ ...props }));
</script>

<style scoped>
.tab-content {
  display: grid;
  justify-content: center;
  padding: 16px;
}
</style>

// svelte/active-list/src/examples/Tabs/Tab.svelte

{#if $activeHref === href}
  <div class="tab-content">
    <slot></slot>
  </div>
{/if}

<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import { TABS, TABS_ACTIVE } from './Tabs.svelte';
  import type { ActiveList } from '@uiloos/core';
  import type { TabInfo } from './types';
  import type { Writable } from 'svelte/store';

  export let name: string;
  export let href: string;

  const tabs = getContext(TABS) as ActiveList<TabInfo>;
  const activeHref = getContext(TABS_ACTIVE) as Writable<string>;

  onMount(() => {
    tabs.push({ name, href});
  });
</script>

<style>
.tab-content {
  display: grid;
  justify-content: center;
  padding: 16px;
}
</style>
