// angular/date-gallery/src/app/examples/calendar/year-calendar/year-calendar.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { monthFormatter } from '../../formatters';
import type { EventData } from '../events';
import { DateGallery, DateGalleryDate, DateGalleryFrame } from '@uiloos/core';

@Component({
  selector: 'year-calendar',
  templateUrl: './year-calendar.component.html',
  styleUrls: ['./year-calendar.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class YearCalendarComponent {
  @Input() dateGallery!: DateGallery<EventData>;

  public monthFormatter!: Intl.DateTimeFormat;

  constructor() {
    this.monthFormatter = monthFormatter;
  }

  public monthClicked(initialDate: Date) {
    this.dateGallery.changeConfig({
      initialDate,
      mode: 'month-six-weeks',
      numberOfFrames: 1,
    });
  }

  public dayClicked(initialDate: Date) {
    this.dateGallery.changeConfig({
      initialDate,
      mode: 'day',
      numberOfFrames: 1,
    });
  }

  public frameTrackBy(index: number, frame: DateGalleryFrame<EventData>) {
    return frame.anchorDate.toISOString();
  }

  public dateTrackBy(index: number, dateObj: DateGalleryDate<EventData>) {
    return dateObj.date.toISOString();
  }
}

<ul class="calendar-year-months">
    <li
     *ngFor="let frame of dateGallery.frames; trackBy: frameTrackBy"
      class="calendar-year"
    >
      <button
        class="calendar-year-monthname"
        (click)="monthClicked(frame.anchorDate)"
      >
        {{ monthFormatter.format(frame.anchorDate) }}
      </button>

      <ul class="calendar-year-daynames">
        <li class="calendar-year-dayname">
          <abbr title="Sunday">S</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Monday">M</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Tuesday">T</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Wednesday">W</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Thursday">T</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Friday">F</abbr>
        </li>
        <li class="calendar-year-dayname">
          <abbr title="Saturday">S</abbr>
        </li>
      </ul>

      <ul class="calendar-year-daycells">
        <!-- 
            Place the days in the correct column, this is only needed
            for the "month" mode because it starts at the first of the 
            month, which may be on an other day than the start of 
            the week.

            The +1 is needed because CSS Grid starts counting at 1.
          -->
        <li
          *ngFor="let dateObj of frame.dates; trackBy: dateTrackBy"
          class="calendar-year-daycell"
          [ngClass]="{ 'has-event': dateObj.hasEvents }"
          [ngStyle]="{ 'grid-column': dateObj.date.getDay() + 1 }"
        >
          <button
            class="calendar-year-daycell-number"
            (click)="dayClicked(dateObj.date)"
          >
            <time [dateTime]="dateObj.date.toISOString()">
              {{ dateObj.date.getDate() }}
            </time>
          </button>
        </li>
      </ul>
    </li>
  </ul>

// react/date-gallery/src/examples/Calendar/YearCalendar/YearCalendar.tsx
import { DateGallery } from "@uiloos/core";
import React from "react";
import { EventData } from "../events";
import { monthFormatter } from "../../formatters";
import classNames from "classnames";
import "./YearCalendar.css";

type Props = {
  dateGallery: DateGallery<EventData>;
};

export function YearCalendar({ dateGallery }: Props) {
  return (
    <ul className="calendar-year-months">
      {dateGallery.frames.map((frame) => (
        <li key={frame.anchorDate.toISOString()} className="calendar-year">
          <button
            className="calendar-year-monthname"
            onClick={() => {
              dateGallery.changeConfig({
                mode: "month-six-weeks",
                numberOfFrames: 1,
                initialDate: frame.anchorDate,
              });
            }}
          >
            {monthFormatter.format(frame.anchorDate)}
          </button>

          <ul className="calendar-year-daynames">
            <li className="calendar-year-dayname">
              <abbr title="Sunday">S</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Monday">M</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Tuesday">T</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Wednesday">W</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Thursday">T</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Friday">F</abbr>
            </li>
            <li className="calendar-year-dayname">
              <abbr title="Saturday">S</abbr>
            </li>
          </ul>

          <ul className="calendar-year-daycells">
            {frame.dates.map((dateObj) => {
              /*
                Place the days in the correct column, this is only needed
                for the "month" mode because it starts at the first of the 
                month, which may be on an other day than the start of 
                the week.

                The +1 is needed because CSS Grid starts counting at 1.
              */
              const gridColumn = dateObj.date.getDay() + 1;

              return (
                <li
                  key={dateObj.date.toISOString()}
                  className={classNames("calendar-year-daycell", {
                    "has-event": dateObj.hasEvents,
                  })}
                  style={{ gridColumn }}
                >
                  <button
                    className="calendar-year-daycell-number"
                    onClick={() =>
                      dateGallery.changeConfig({
                        initialDate: dateObj.date,
                        mode: "day",
                        numberOfFrames: 1,
                      })
                    }
                  >
                    <time dateTime={dateObj.date.toISOString()}>
                      {dateObj.date.getDate()}
                    </time>
                  </button>
                </li>
              );
            })}
          </ul>
        </li>
      ))}
    </ul>
  );
}
