// react/active-list/src/examples/SnapCarousel/Progress.tsx
import { ActiveListAutoPlay } from "@uiloos/core";
import { useEffect, useRef } from "react";

type Props = {
  autoPlay: ActiveListAutoPlay;
  hide: boolean;
};

export function Progress({ autoPlay, hide }: Props) {
  const ref = useRef<HTMLDivElement | null>(null);

  const { isPlaying, duration } = autoPlay;

  // Activate the animation
  useEffect(() => {
    if (ref.current) {
      ref.current.style.animation = `progress ${duration}ms linear`;
    }
  }, [duration]);

  // Trigger progress animation based on isPlaying state
  useEffect(() => {
    if (ref.current) {
      if (isPlaying) {
        ref.current.style.animationPlayState = "running";
      } else {
        ref.current.style.animationPlayState = "paused";
      }
    }
  }, [isPlaying]);

  return (
    <div
      ref={ref}
      className="snap-carousel-progress"
      style={{ background: hide ? "white" : undefined }}
    ></div>
  );
}

// vue/active-list/src/examples/SnapCarousel/Progress.vue
<template>
  <div
    ref="progressElement"
    class="snap-carousel-progress"
    :class="{ white: hide }"
  ></div>
</template>

<script setup lang="ts">
import { ref, watchEffect } from "vue";

interface Props {
  duration: number;
  isPlaying: boolean;
  hide: boolean;
}

const props = defineProps<Props>();

const progressElement = ref<HTMLDivElement | null>(null);

// Activate the animation
watchEffect(() => {
  if (progressElement.value) {
    progressElement.value.style.animation = `progress ${props.duration}ms linear`;
  }
});

// Trigger progress animation based on isPlaying state
watchEffect(() => {
  if (progressElement.value) {
    if (props.isPlaying) {
      progressElement.value.style.animationPlayState = "running";
    } else {
      progressElement.value.style.animationPlayState = "paused";
    }
  }
});
</script>

<style>
.snap-carousel-progress {
  margin-bottom: 4px;
  width: 512px;
  height: 8px;
  background: linear-gradient(
    to right,
    rgb(107 33 168) 50%,
    rgb(102, 102, 102) 50%
  );
  background-size: 200% 100%;
}

.snap-carousel-progress.white {
  background: white;
}

@keyframes progress {
  from {
    background-position: right bottom;
  }
  to {
    background-position: left bottom;
  }
}
</style>
