// angular/view-channel/src/app/examples/example-modals/car-modal/car-modal.component.ts
import { Component, Input } from '@angular/core';
import { ViewChannelView } from '@uiloos/core';
import { ModalComponent, ModalData } from '../../modal/types';

type CarModalResult = 'ford' | 'audi' | 'toyota';

@Component({
  selector: 'car-modal',
  templateUrl: './car-modal.component.html',
  standalone: true
})
export class CarModalComponent implements ModalComponent<CarModalResult, {}> {
  @Input() view!: ViewChannelView<ModalData<any>, CarModalResult>;

  @Input() data!: {};

  onCarClicked(car: CarModalResult) {
    this.view.dismiss(car);
  }
}

<ol>
  <li>
    <button (click)="onCarClicked('ford')">Ford</button>
  </li>
  <li>
    <button (click)="onCarClicked('audi')">Audi</button>
  </li>
  <li>
    <button (click)="onCarClicked('toyota')">Toyota</button>
  </li>
</ol>

// svelte/view-channel/src/routes/components/example-modals/CarModal.svelte
<ol>
  <li>
    <button on:click={() => onCarClicked('ford')}>Ford</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('audi')}>Audi</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('toyota')}>Toyota</button>
  </li>
</ol>

<script lang="ts">
import type { ModalComponent } from "../modal/types";
import type { ViewChannelView } from "@uiloos/core";

type CarModalResult = "ford" | "audi" | "toyota";

export let view: ViewChannelView<unknown, CarModalResult>;

function onCarClicked(car: CarModalResult) {
  view.dismiss(car);
}
</script>
