// react/view-channel/src/ExampleModals/CarModal.tsx
import { ModalComponentProps } from '../Modal/types';

type Props = {};

type CarModalResult = 'ford' | 'audi' | 'toyota';

export function CarModal(props: ModalComponentProps<Props, CarModalResult>) {
  function onCarClicked(car: CarModalResult) {
    props.view.dismiss(car);
  }

  return (
    <ol>
      <li>
        <button onClick={() => onCarClicked('ford')}>Ford</button>
      </li>
      <li>
        <button onClick={() => onCarClicked('audi')}>Audi</button>
      </li>
      <li>
        <button onClick={() => onCarClicked('toyota')}>Toyota</button>
      </li>
    </ol>
  );
}

// svelte/view-channel/src/routes/components/example-modals/CarModal.svelte
<ol>
  <li>
    <button on:click={() => onCarClicked('ford')}>Ford</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('audi')}>Audi</button>
  </li>
  <li>
    <button on:click={() => onCarClicked('toyota')}>Toyota</button>
  </li>
</ol>

<script lang="ts">
import type { ModalComponent } from "../modal/types";
import type { ViewChannelView } from "@uiloos/core";

type CarModalResult = "ford" | "audi" | "toyota";

export let view: ViewChannelView<unknown, CarModalResult>;

function onCarClicked(car: CarModalResult) {
  view.dismiss(car);
}
</script>
