// vue/date-gallery/src/examples/Dialog/Dialog.vue
<template>
  <dialog
    ref="dialog"
    @click="closeDialog($event)"
    @keydown="
      {
        emit('keydown', $event);
      }
    "
  >
    <slot></slot>
  </dialog>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";

let dialog = ref<HTMLDialogElement | null>(null);

const emit = defineEmits<{
  (e: "keydown", element: KeyboardEvent): void;
  (e: "close"): void;
}>();

onMounted(() => {
  if (dialog.value) {
    dialog.value.showModal();
  }
});

function closeDialog(event: MouseEvent) {
  if (
    event.target instanceof HTMLElement &&
    event.target.nodeName === "DIALOG"
  ) {
    if (dialog.value) {
      dialog.value.close();
      emit("close");
    }
  }
}
</script>

// svelte/date-gallery/src/examples/Dialog/Dialog.svelte
<dialog bind:this={dialog} on:click={closeDialog} on:keydown={onKeyDown}>
  <slot />
</dialog>

<script lang="ts">
  import {onMount} from 'svelte';

  let dialog: HTMLDialogElement | null = null;
  export let onKeyDown: (e: KeyboardEvent) => void = () => undefined;
  export let onClose: () => void;

  onMount(() => {
    if (dialog) {
      dialog.showModal();
    }
  });

  function closeDialog(event: MouseEvent) {
    if (event.target && event.target instanceof HTMLElement && event.target.nodeName === "DIALOG") {
      if (dialog) {
        dialog.close();
      }

      onClose();
    }
}
</script>
