// angular/active-list/src/app/examples/gallery/gallery.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { ActiveList } from '@uiloos/core';
import { GalleryImage } from './types';

@Component({
  selector: 'gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class GalleryComponent implements OnInit {
  @Input() images!: GalleryImage[];

  public gallery!: ActiveList<GalleryImage>;

  ngOnInit(): void {
    const self = this;

    this.gallery = new ActiveList({
      contents: this.images,
      active: this.images[0],
    });
  }
}

<div class="gallery-example">
    <div class="gallery-selected">
      <img
        width="1920"
        height="1280"
        [src]="gallery.lastActivated?.src"
        alt="{{gallery.lastActivated?.alt}}"
      />
    </div>

    <ul class="gallery-items">
      <li *ngFor="let content of gallery.contents">
        <button (click)="content.activate()">
          <img
            width="1920"
            height="1280"
            [src]="content.value.src"
            alt="{{content.value.alt}}"
          />
        </button>
      </li>
    </ul>
  </div>

// react/active-list/src/examples/Gallery/Gallery.tsx
import { useActiveList } from "@uiloos/react";
import { GalleryImage } from "./types";
import "./Gallery.css";

type Props = {
  images: GalleryImage[];
};

export function Gallery({ images }: Props) {
  const gallery = useActiveList({
    contents: images,
    active: images[0],
  });

  return (
    <div className="gallery-example">
      <div className="gallery-selected">
        <img
          width="1920"
          height="1280"
          src={gallery.lastActivated?.src}
          alt={gallery.lastActivated?.alt}
        />
      </div>

      <ul className="gallery-items">
        {gallery.contents.map((content) => (
          <li key={content.value.src}>
            <button onClick={() => content.activate()}>
              <img
                width="1920"
                height="1280"
                src={content.value.src}
                alt={content.value.alt}
              />
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
