// angular/date-gallery/src/app/examples/datepicker/datepicker-dialog/datepicker-dialog.component.ts
import { Component, Output, EventEmitter, Input, OnInit } from '@angular/core';

import { isValid } from 'date-fns';
import { DateGallery, DateGalleryDate } from '@uiloos/core';
import { dateFormatter } from '../../formatters';
import { parseAsDate } from './../utils';
import { MyDialogComponent } from '../../my-dialog/my-dialog.component';
import { MonthSelectComponent } from '../month-select/month-select.component';
import { CommonModule } from '@angular/common';
import { YearInputComponent } from '../year-input/year-input.component';

@Component({
  selector: 'datepicker-dialog',
  templateUrl: './datepicker-dialog.component.html',
  styleUrls: ['./datepicker-dialog.component.css'],
  standalone: true,
  imports: [
    CommonModule,
    MyDialogComponent,
    MonthSelectComponent,
    YearInputComponent,
  ],
})
export class DatepickerDialogComponent implements OnInit {
  @Output() close = new EventEmitter<void>();

  @Input() value!: string;
  @Output() selected = new EventEmitter<string>();

  @Input() min?: Date;
  @Input() max?: Date;

  public dateGallery!: DateGallery<unknown>;

  public dateFormatter!: Intl.DateTimeFormat;

  ngOnInit() {
    this.dateFormatter = dateFormatter;

    let initialDate = new Date();
    if (this.value) {
      const date = parseAsDate(this.value);

      if (isValid(date)) {
        initialDate = date as Date;
      }
    }

    const self = this;

    this.dateGallery = new DateGallery({
      mode: 'month',
      initialDate,
      selectedDates: [initialDate],
      maxSelectionLimit: 1,
      canSelect(dateObj: DateGalleryDate<unknown>) {
        if (self.min && dateObj.date < self.min) {
          return false;
        } else if (self.max && dateObj.date > self.max) {
          return false;
        }

        return true;
      },
    });
  }

  onDateClicked(dateObj: DateGalleryDate<unknown>) {
    const date = dateFormatter.format(dateObj.date);

    this.selected.emit(date);
    this.close.emit();
  }

  public closeDialog() {
    this.close.emit();
  }

  public onKeydown(event: KeyboardEvent) {
    // Do not interfere with the year <input>
    if (
      event.target &&
      event.target instanceof HTMLElement &&
      event.target.nodeName &&
      event.target.nodeName === 'INPUT'
    ) {
      return;
    }

    // Stop the propagation here so not all elements
    // are called for better performance.
    event.stopPropagation();

    if (
      ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)
    ) {
      // Copy date as not to mutate the selected date.
      const date = new Date(this.dateGallery.selectedDates[0]);

      // Mutate the date based on the arrow keys
      if (event.key === 'ArrowLeft') {
        date.setDate(date.getDate() - 1);
      } else if (event.key === 'ArrowRight') {
        date.setDate(date.getDate() + 1);
      } else if (event.key === 'ArrowUp') {
        date.setDate(date.getDate() - 7);
      } else if (event.key === 'ArrowDown') {
        date.setDate(date.getDate() + 7);
      }

      // Select the date so it highlights in blue.
      this.dateGallery.selectDate(date);

      // Change the initialDate (changes the frames) so the user
      // can navigate to other months.
      this.dateGallery.changeConfig({ initialDate: date });
    } else if (event.key === 'Enter') {
      // When enter is pressed close the dialog and set
      // the value to the selected date.

      // We do not want the dialog to open again.
      event.preventDefault();

      const date = dateFormatter.format(this.dateGallery.selectedDates[0]);

      this.selected.emit(date);
      this.close.emit();
    }
  }

  dateTrackBy(index: number, dateObj: DateGalleryDate<unknown>) {
    return dateObj.date.toISOString();
  }
}

<my-dialog (keydown)="onKeydown($event)" (close)="closeDialog()">
  <div class="datepicker-dialog-content">
    <div class="topbar">
      <button
        aria-label="previous"
        type="button"
        (click)="dateGallery.previous()"
      >
        ‹
      </button>
      <span>
        <month-select [dateGallery]="dateGallery" />
        <year-input
          [dateGallery]="dateGallery"
          [year]="dateGallery.firstFrame.anchorDate.getFullYear()"
        />
      </span>
      <button aria-label="next" type="button" (click)="dateGallery.next()">
        ›
      </button>
    </div>

    <ul class="daygrid">
      <li>
        <abbr title="Sunday">S</abbr>
      </li>
      <li>
        <abbr title="Monday">M</abbr>
      </li>
      <li>
        <abbr title="Tuesday">T</abbr>
      </li>
      <li>
        <abbr title="Wednesday">W</abbr>
      </li>
      <li>
        <abbr title="Thursday">T</abbr>
      </li>
      <li>
        <abbr title="Friday">F</abbr>
      </li>
      <li>
        <abbr title="Saturday">S</abbr>
      </li>
    </ul>

    <ul class="dates daygrid">
      <li
        *ngFor="let dateObj of dateGallery.firstFrame.dates; trackBy: dateTrackBy"
        [ngStyle]="{ 'grid-column': dateObj.date.getDay() + 1 }"
      >
        <button
          attr.aria-label="Select {{dateFormatter.format(dateObj.date)}}"
          type="button"
          [ngClass]="{ selected: dateObj.isSelected, today: dateObj.isToday }"
          [disabled]="!dateObj.canBeSelected"
          (click)="onDateClicked(dateObj)"
        >
          <time [dateTime]="dateObj.date.toISOString()">
            {{ dateObj.date.getDate() }}
          </time>
        </button>
      </li>
    </ul>

    <div class="bottombar">
      <button type="button" (click)="closeDialog()">Cancel</button>
      <button type="button" (click)="dateGallery.today()">Today</button>
    </div>
  </div>
</my-dialog>

// react/date-gallery/src/examples/Datepicker/DatepickerDialog.tsx
import { useDateGallery } from "@uiloos/react";
import React, { KeyboardEvent } from "react";
import { isValid } from "date-fns";
import classNames from "classnames";
import { DateGalleryDate } from "@uiloos/core";
import { dateFormatter } from "../formatters";
import { MonthSelect } from "./MonthSelect";
import { YearInput } from "./YearInput";
import { Dialog } from "../Dialog/Dialog";
import { parseAsDate } from "./utils";

type Props = {
  value: string;
  onChange(value: string): void;
  onClose: () => void;
  min?: Date;
  max?: Date;
};

export function DatepickerDialog({
  value,
  onChange,
  onClose,
  min,
  max,
}: Props) {
  let initialDate = new Date();
  if (value) {
    const date = parseAsDate(value);

    if (isValid(date)) {
      initialDate = date as Date;
    }
  }

  const dateGallery = useDateGallery({
    mode: "month",
    initialDate,
    selectedDates: [initialDate],
    maxSelectionLimit: 1,
    canSelect(dateObj) {
      if (min && dateObj.date < min) {
        return false;
      } else if (max && dateObj.date > max) {
        return false;
      }

      return true;
    },
  });

  function onDateClicked(dateObj: DateGalleryDate<unknown>) {
    const date = dateFormatter.format(dateObj.date);
    onChange(date);
    onClose();
  }

  function onKeyDown(event: KeyboardEvent<HTMLDialogElement>) {
    // Do not interfere with the year <input>
    if (
      event.target &&
      event.target instanceof HTMLElement &&
      event.target.nodeName === "INPUT"
    ) {
      return;
    }

    // Stop the propagation here so not all elements
    // are called for better performance.
    event.stopPropagation();

    if (
      ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)
    ) {
      // Copy date as not to mutate the selected date.
      const date = new Date(dateGallery.selectedDates[0]);

      // Mutate the date based on the arrow keys
      if (event.key === "ArrowLeft") {
        date.setDate(date.getDate() - 1);
      } else if (event.key === "ArrowRight") {
        date.setDate(date.getDate() + 1);
      } else if (event.key === "ArrowUp") {
        date.setDate(date.getDate() - 7);
      } else if (event.key === "ArrowDown") {
        date.setDate(date.getDate() + 7);
      }

      // Select the date so it highlights in blue.
      dateGallery.selectDate(date);

      // Change the initialDate (changes the frames) so the user
      // can navigate to other months.
      dateGallery.changeConfig({ initialDate: date });
    } else if (event.key === "Enter") {
      // When enter is pressed close the dialog and set
      // the value to the selected date.

      // We do not want the dialog to open again.
      event.preventDefault();

      const date = dateFormatter.format(dateGallery.selectedDates[0]);

      onChange(date);
      onClose();
    }
  }

  return (
    <Dialog onKeyDown={onKeyDown} onClose={onClose}>
      <div className="datepicker-dialog-content">
        <div className="topbar">
          <button
            aria-label="previous"
            type="button"
            onClick={() => dateGallery.previous()}
          >
            ‹
          </button>
          <span>
            <MonthSelect dateGallery={dateGallery} />
            <YearInput dateGallery={dateGallery} />
          </span>
          <button
            aria-label="next"
            type="button"
            onClick={() => dateGallery.next()}
          >
            ›
          </button>
        </div>

        <ul className="daygrid">
          <li>
            <abbr title="Sunday">S</abbr>
          </li>
          <li>
            <abbr title="Monday">M</abbr>
          </li>
          <li>
            <abbr title="Tuesday">T</abbr>
          </li>
          <li>
            <abbr title="Wednesday">W</abbr>
          </li>
          <li>
            <abbr title="Thursday">T</abbr>
          </li>
          <li>
            <abbr title="Friday">F</abbr>
          </li>
          <li>
            <abbr title="Saturday">S</abbr>
          </li>
        </ul>

        <ul className="dates daygrid">
          {dateGallery.firstFrame.dates.map((dateObj) => (
            <li
              key={dateObj.date.toISOString()}
              style={{ gridColumn: dateObj.date.getDay() + 1 }}
            >
              <button
                aria-label={`Select ${dateFormatter.format(dateObj.date)}`}
                type="button"
                className={classNames({
                  selected: dateObj.isSelected,
                  today: dateObj.isToday,
                })}
                disabled={!dateObj.canBeSelected}
                onClick={() => onDateClicked(dateObj)}
              >
                <time dateTime={dateObj.date.toISOString()}>
                  {dateObj.date.getDate()}
                </time>
              </button>
            </li>
          ))}
        </ul>

        <div className="bottombar">
          <button type="button" onClick={() => onClose()}>
            Cancel
          </button>
          <button type="button" onClick={() => dateGallery.today()}>
            Today
          </button>
        </div>
      </div>
    </Dialog>
  );
}
