// svelte/date-gallery/src/examples/Datepicker/YearInput.svelte
<input
  value={year}
  on:change={(e) => {
    if (e.target instanceof HTMLInputElement) {
      year = e.target.value;
    }
  }}
  on:keyup={(e) => {
    if (e.key === "Enter" && e.target instanceof HTMLInputElement) {
      onYearInputChanged(e.target.value);
    }
  }}
  on:blur={(e) => {
    if (e.target instanceof HTMLInputElement) {
      onYearInputChanged(e.target.value);
    }
  }}
/>

<script lang="ts">
  import type { DateGallery } from "@uiloos/core";
  import { onMount } from 'svelte';

  export let dateGallery: DateGallery<unknown>;
    
  let year: string = new Date().getFullYear().toString();

  function onYearInputChanged(value: string) {
    let newYear = parseInt(value, 10);

    if (isNaN(newYear)) {
        newYear = new Date().getFullYear();
        year = newYear.toString();
    }

    const date = new Date(
        newYear,
        dateGallery.firstFrame.anchorDate.getMonth(),
        dateGallery.firstFrame.anchorDate.getDate(),
    );

    dateGallery.changeConfig({ initialDate: date });
  }

   $: updateYear(dateGallery.firstFrame.anchorDate.getFullYear());

   function updateYear(newYear: number) {
     year = newYear.toString();
   }

   onMount(() => {
    year = dateGallery.firstFrame.anchorDate.getFullYear().toString();
  });

</script>

<style>
  input {
    border: solid 1px black;
    padding: 4px;
    width: 42px;
  }
</style>

// react/date-gallery/src/examples/Datepicker/YearInput.tsx
import React, { useState, useEffect } from "react";
import { DateGallery } from "@uiloos/core";

type Props = {
  dateGallery: DateGallery<unknown>;
};

export function YearInput({ dateGallery }: Props) {
  function onYearInputChanged(value: string) {
    let year = parseInt(value, 10);

    if (isNaN(year)) {
      year = new Date().getFullYear();
      setYear(year.toString());
    }

    const date = new Date(
      year,
      dateGallery.firstFrame.anchorDate.getMonth(),
      dateGallery.firstFrame.anchorDate.getDate(),
    );

    dateGallery.changeConfig({ initialDate: date });
  }

  const [year, setYear] = useState(
    dateGallery.firstFrame.anchorDate.getFullYear().toString(),
  );

  useEffect(() => {
    setYear(dateGallery.firstFrame.anchorDate.getFullYear().toString());
  }, [dateGallery.firstFrame.anchorDate]);

  return (
    <input
      className="year"
      value={year}
      onChange={(e) => setYear(e.target.value)}
      onKeyUp={(e) => {
        if (e.key === "Enter" && e.target instanceof HTMLInputElement) {
          onYearInputChanged(e.target.value);
        }
      }}
      onBlur={(e) => onYearInputChanged(e.target.value)}
    />
  );
}
