// vue/date-gallery/src/Tabs/Tab.vue
<template>
  <div v-if="activeHref === props.href" class="tab-content">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { ActiveList } from "@uiloos/core";
import { inject, ref, unref, Ref } from "vue";
import { activeInjectionKey, tabInjectionKey } from "./util";
import type { TabInfo } from "./types";

interface Props {
  name: string;
  href: string;
}

const props = defineProps<Props>();

const tabs = unref(inject(tabInjectionKey) as ActiveList<TabInfo>);
const activeHref = inject(activeInjectionKey) as Ref<string>;

ref(tabs.push({ ...props }));
</script>

<style scoped>
.tab-content {
  padding: 16px;
}
</style>

// react/active-list/src/examples/Tabs/Tab.tsx
import { ReactNode, useContext, useEffect } from "react";
import { TabsActiveListContext, TabsActiveContext } from "./TabsContext";

export type Props = {
  name: ReactNode;
  href: string;
  children: ReactNode;
};

export function Tab({ children, name, href }: Props) {
  const tabs = useContext(TabsActiveListContext);

  useEffect(() => {
    if (!tabs.contents.some((c) => c.value.name === name)) {
      tabs.push({ name, href });
    }
  }, []);

  const activeHref = useContext(TabsActiveContext);

  if (activeHref !== href) {
    return null;
  }

  return <div className="tab-content">{children}</div>;
}
